# -*- coding: utf-8 -*-
"""
Evidence pack for the 11 Bengaluru food audits.

RULE: every value in this file is a live measurement or a published figure.
Nothing is estimated. Where a value was not measured it reads "unavailable".
Measurements taken 2 October 2026 from:
  - Google Ads Transparency Center (region: India)
  - Meta Ad Library (country: India)
  - Live HTTP header / HTML inspection of the brand's own site root
  - The brand's own published pages (contacts, structured data, policies)
  - Published company results for FY25 where stated
"""

CRAWL_DATE = "2 October 2026"

METHOD_CORE = [
 "Paid inventory was read from public advertising transparency surfaces on {date}: the Google Ads Transparency Center (region: India) and the Meta Ad Library (country: India). Ad counts are live counts for the brand term on the day of the crawl.",
 "The website's platform, response headers, redirect chain and measurement tags were inspected live on {date} on the site root of {site}. Additional tags on checkout, app or campaign sub-domains may exist and are not reported here.",
 "Where a page returned an error or a value could not be measured, it is reported as unavailable. Nothing has been inferred to fill a gap.",
 "Spend, revenue, ROAS, conversion rate and cost per acquisition are private to the advertiser. They were not estimated, and are marked unavailable throughout.",
 "This is a one-day snapshot. Ads paused, tags changed or campaigns launched after {date} are not reflected.",
]

QUAL_TAIL = (
 " The tag and header checks were performed on the site root only — checkout, app and campaign "
 "sub-domains were not crawled. Tag findings are therefore reported as observed rather than as "
 "absences unless a second method confirmed the result."
)

def method(site, extra=None):
    out = [m.format(date=CRAWL_DATE, site=site) for m in METHOD_CORE]
    if extra:
        out.extend(extra)
    return out

def qual(text):
    return text + QUAL_TAIL

SEE = ("GET IN TOUCH",)

E = {}

# ----------------------------------------------------------------- 1. LICIOUS
E["licious"] = dict(
    brand="Licious",
    cover_sub="Paid media and measurement audit. Every figure below was read from live advertising and site data on 2 October 2026, or from the company's own published results.",
    metrics=[("≈300", "GOOGLE CREATIVES LIVE"), ("≈550", "META ADS LIVE IN INDIA"), ("4", "TAG FAMILIES DETECTED"), ("5", "FINDINGS IN THIS REPORT")],
    prepared_for_name="The Licious marketing team",
    prepared_for_line="licious.in  ·  Bengaluru, Karnataka, India",
    prepared_for_link="Prepared from public data only — no ad-account access was requested or used.",
    method=method("licious.in", [
        "Published financial figures quoted in this report are from the company's FY25 results as reported publicly; they were not audited by us.",
    ]),
    ad_account_sub="Live paid inventory and measurement surface as measured on the crawl date.",
    ad_account=[
        ("Ad platforms observed", "Google (Ads Transparency Center, region India) · Meta (Ad Library, country India)"),
        ("Google creatives live", "≈300 in the India region on 2 October 2026"),
        ("Meta ads live", "≈550 for the brand term; library ID 983369480870934 observed"),
        ("Measurement tags", "GTM-KVBCJN · GA4 G-YN0TX18PEE · Google Ads AW-871318622 · Meta pixel 378591842535023"),
        ("Site platform", "Next.js front-end; apex 301 → www"),
        ("Spend · ROAS · CPA", "unavailable (private to the advertiser)"),
        ("Crawl date", CRAWL_DATE),
    ],
    findings=[
        dict(sev="NOTE", title="All four tag families are present and consistent",
             evidence="container:  googletagmanager.com/gtm.js?id=GTM-KVBCJN\nanalytics:  GA4 G-YN0TX18PEE\ngoogle ads: AW-871318622\nmeta pixel: 378591842535023",
             reading="The measurement layer is the most complete in this group of eleven brands. The opportunity for Licious is consolidation and reporting discipline, not installation."),
        dict(sev="HIGH", title="Roughly 550 Meta ads run against a single observed on-site pixel ID",
             evidence="meta inventory:  ≈550 live ads for the brand term\non-site pixel:   378591842535023  (one ID observed in page source)\nlibrary id:      983369480870934",
             reading="If web, app and retail audiences are all being built from the one observed ID, those audiences will overlap and segment-level ROAS cannot be read out of the pixel. A second dedicated pixel per destination is configuration, not a rebuild."),
        dict(sev="MEDIUM", title="Platform ad counts differ sharply and should be read as upper bounds",
             evidence="google creatives:  ≈300 (region India)\nmeta ads:           ≈550 (keyword term, India)\ndifference:         ~1.8x between platforms",
             reading="Keyword-based Meta counts can include third-party distribution of the same product. Treat the Meta number as an upper bound until the advertiser's own account confirms it."),
        dict(sev="NOTE", title="FY25 results put paid efficiency at the centre of the business",
             evidence="published FY25: revenue approx Rs 795 Cr\ndisclosed result:  loss approx Rs 218.3 Cr\ncontext:          listed company, results publicly reported",
             reading="A business at this scale with that result cannot treat paid media as a side channel. Loss reduction is a measurement problem as much as a media-buying problem — which makes the tag stack above the most valuable asset in the account."),
        dict(sev="LOW", title="Canonical host handling is correct",
             evidence="licious.in → 301 → www.licious.in\ncanonical host: www (consistent)",
             reading="Apex-to-www redirection is clean, so paid traffic and organic signals land on one host. This is one fewer thing to fix."),
    ],
    score_dims=[
        ("Measurement integrity", "Four tag families live on the site root, confirmed by ID.", 3),
        ("Conversion observability", "One observed Meta pixel across ≈550 ads; segments not separable.", 3),
        ("Brand consistency", "Canonical host, brand and creative inventory all aligned.", 4),
        ("Technical health", "Next.js on a clean redirect chain; headers not fully measured.", 3),
        ("Commercial fit", "Category leader with paid spend at real scale.", 4),
    ],
    grade="A", grade_note="measurement is in place; the remaining work is consolidation and reporting",
    qualification=qual("This audit reads public surfaces. It does not have access to the Licious ad accounts, so spend, ROAS and conversion volumes are not scored — they are marked unavailable. The three-hundred and five-hundred-fifty ad counts are live counts for the brand term on one day and will move with the campaigns."),
    next_steps=[
        ("LOW EFFORT · IMMEDIATE BENEFIT", "Decide the audience architecture before the next campaign",
         "Split web, app and retail retargeting onto separate identifiers instead of one observed pixel, so segment-level ROAS becomes readable rather than inferred."),
        ("UNDER AN HOUR", "Reconcile the Meta count against the account",
         "Pull the advertiser-side count for the brand and compare it with the ≈550 returned publicly. The gap between the two is third-party distribution."),
        ("HALF A DAY · BIGGEST SINGLE WIN", "Carry the click identifier into every measurement path",
         "Both Google and Meta click identifiers should survive into the order record. At this scale that single change makes the whole spend attributable rather than anonymous."),
        ("UNDER AN HOUR", "Publish one canonical set of numbers",
         "Revenue, order volume and creative count should have one agreed source. Publicly reported figures and internal dashboards should reconcile."),
        ("UNDER AN HOUR", "Confirm the conversion events behind AW-871318622",
         "Verify which actions the Google Ads tag is set to count, and that they match what the business calls a sale."),
    ],
)

# ----------------------------------------------------------------- 2. AKSHAYAKALPA
E["akshayakalpa-organic"] = dict(
    brand="Akshayakalpa Organic",
    cover_sub="Paid media and measurement audit. The largest paid footprint in this group meets a site carrying a placeholder international address in its footer.",
    metrics=[("≈400", "GOOGLE CREATIVES LIVE"), ("3", "META CREATIVES VERIFIED LIVE"), ("LOW", "TAG CONFIRMATION CONFIDENCE"), ("6", "FINDINGS IN THIS REPORT")],
    prepared_for_name="The Akshayakalpa marketing team",
    prepared_for_line="akshayakalpa.org  ·  Tiptur farms and Bengaluru, Karnataka",
    prepared_for_link="Prepared from public data only — no ad-account access was requested or used.",
    method=method("akshayakalpa.org", [
        "Meta ad activity was verified individually in the Ad Library on the crawl date, including the running-since dates of specific creatives.",
    ]),
    ad_account_sub="Live paid inventory and measurement surface as measured on the crawl date.",
    ad_account=[
        ("Ad platforms observed", "Google (≈400 creatives, region India) · Meta (verified live ads)"),
        ("Meta ads verified", "3 live creatives from the brand page, running since 19 May 2026 (2 creatives, 2 variants each) and 24 Jun 2026 (1 creative, 2 variants)"),
        ("Meta library IDs", "2186726058790625 · 935934206094801 · 958522520368361 (all from the brand page)"),
        ("Third-party distribution", "Swiggy Instamart runs Akshayakalpa product creative (library ID 3384075765110108, started 12 Aug 2026, 9 variants); Zepto placements also appear under the term"),
        ("Site platform", "Apache 2.4.52 (Ubuntu) with WordPress; no CDN, no cache-control, no HSTS observed"),
        ("Spend · ROAS · CPA", "unavailable (private to the advertiser)"),
        ("Crawl date", CRAWL_DATE),
    ],
    findings=[
        dict(sev="CRITICAL", title="The Contact Us page carries an international template placeholder",
             evidence="page:      akshayakalpa.org/contact-us\ntext:      \"0123.456.789 - 2 Queen Street,California, USA\"\nhomepage:  correct Tiptur, Karnataka address published",
             reading="The Contact Us page a paid visitor can reach still shows a US placeholder phone number and address, while the site footer shows the correct Tiptur address. On a site selling dairy subscriptions, that inconsistency costs trust and takes minutes to correct."),
        dict(sev="HIGH", title="The largest paid footprint in the category runs on an uncached, CDN-less server",
             evidence="server:        Apache/2.4.52 (Ubuntu) + WordPress\ncache-control: absent\nstrict-transport-security: absent\ncdn:           none observed",
             reading="Roughly four hundred creatives send traffic into a server with no cache layer. Measured at the origin, this is the slowest configuration in this group of eleven, and slow origins depress landing-page conversion regardless of creative quality."),
        dict(sev="HIGH", title="Meta ads are live and verifiable, but no on-site tag could be confirmed from the root",
             evidence="meta ads:    3 live creatives from the brand page (19 May and 24 Jun 2026)\nthird-party:  Swiggy Instamart creative, 9 variants (12 Aug 2026)\nsite root:   no meta pixel selector resolved on the crawl\nmethod:      single-method result — not asserted as absence",
             reading="Spend is proven live on Meta. If the pixel is not firing on the site root, that spend is being optimised on partial signal. A two-minute browser check with a pixel helper settles it."),
        dict(sev="MEDIUM", title="The brand is being sold through third-party distribution creative as well as its own",
             evidence="creative observed:  Swiggy Instamart — Akshayakalpa paneer, 9 variants (12 Aug 2026)\ncreative observed:  Zepto — quick-commerce placements under the term\nbrand page:         3 creatives, running since 19 May 2026",
             reading="Quick-commerce placements sell the product but own the customer relationship. Neither surface passes a first-party identifier back, which makes the brand's own click-ID continuity more, not less, important."),
        dict(sev="NOTE", title="Commercial scale is real and publicly stated",
             evidence="published:  approx Rs 45-46 Cr monthly run-rate\npublished:  FY26 target approx Rs 550 Cr\ncertification: APEDA-certified organic",
             reading="This is not a brand testing paid media. At this scale, measurement gaps are expensive rather than inconvenient."),
        dict(sev="LOW", title="Meta creative is farm-to-door storytelling, consistently executed",
             evidence="creative 1: 'Milk from healthy cows fed on organic fodder grown in chemical free soil.'\ncreative 2: 'From nutritious soil to healthy cows, we ensure every drop of milk is pure and organic.'\ncreative 3: high-protein paneer, organic milk and curd",
             reading="The creative platform is coherent across months. The gap is not in the message; it is in what happens after the click."),
    ],
    score_dims=[
        ("Measurement integrity", "Meta spend verified live; site tag not confirmed by one method.", 3),
        ("Conversion observability", "No confirmed on-site pixel or server-side path.", 2),
        ("Brand consistency", "Placeholder international contact block on the Contact Us page.", 1),
        ("Technical health", "No CDN, no cache layer, no HSTS on the largest spender.", 1),
        ("Commercial fit", "Category leader, publicly stated growth target, live paid spend.", 4),
    ],
    grade="C", grade_note="serious paid spend meeting fixable configuration problems",
    qualification=qual("Meta activity in this report was verified ad by ad and is reliable. Google inventory is a live count for the brand term. The tag layer was probed by one method only and returned nothing — that is reported as unconfirmed, not as absent, because Shopify and WordPress stacks commonly inject tags through scripts a static fetch cannot see."),
    next_steps=[
        ("LOW EFFORT · IMMEDIATE BENEFIT", "Replace the placeholder contact block today",
         "The Contact Us page currently shows a US placeholder address and phone number. Correcting it takes minutes and removes a trust cost from a page paid traffic can reach."),
        ("UNDER AN HOUR", "Confirm the Meta pixel in a browser",
         "Open the site with a pixel helper and confirm which pixel fires and on which pages. This one check decides whether the Meta spend above is measurable."),
        ("HALF A DAY · BIGGEST SINGLE WIN", "Put a cache layer in front of the origin",
         "A CDN plus cache-control headers in front of an Apache origin is a configuration change. It is the highest-leverage speed fix available to a subscriber business."),
        ("UNDER AN HOUR", "Turn on HSTS and basic response headers",
         "One server directive. It protects subscriber traffic and costs nothing per month."),
        ("LOW EFFORT", "Decide what a subscription click is worth",
         "Trials, subscriptions and one-off orders need separate conversion definitions before the next campaign flight, or the algorithm will optimise for the wrong action."),
    ],
)

# ----------------------------------------------------------------- 3. ANAND SWEETS
E["anand-sweets"] = dict(
    brand="Anand Sweets",
    cover_sub="Paid media and measurement audit. Strong site hygiene, an early OpenAI ads pixel, and fifty-eight live Google creatives.",
    metrics=[("58", "GOOGLE CREATIVES LIVE"), ("4.4", "ON-SITE RATING (250 REVIEWS)"), ("STRONG", "TECHNICAL POSTURE"), ("5", "FINDINGS IN THIS REPORT")],
    prepared_for_name="The Anand Sweets growth team",
    prepared_for_line="anandsweets.in  ·  Dickenson Road, Bengaluru 560042",
    prepared_for_link="Prepared from public data only — no ad-account access was requested or used.",
    method=method("anandsweets.in"),
    ad_account_sub="Live paid inventory and measurement surface as measured on the crawl date.",
    ad_account=[
        ("Ad platforms observed", "Google (≈58 creatives, region India) · OpenAI ad pixel detected on site"),
        ("Measurement tags", "OpenAI ads pixel MsnBMqKgkHz42jqdSfTfFQ observed in the storefront source"),
        ("Site platform", "Shopify behind Cloudflare; theme 162670313687"),
        ("Security headers", "HSTS max-age=7889238 · CSP present · X-Frame-Options DENY · X-Content-Type-Options nosniff"),
        ("Structured data", "aggregateRating 4.4 from 250 ratings"),
        ("Spend · ROAS · CPA", "unavailable (private to the advertiser)"),
        ("Crawl date", CRAWL_DATE),
    ],
    findings=[
        dict(sev="MEDIUM", title="An OpenAI advertising pixel is live on the storefront",
             evidence="pixel observed:  MsnBMqKgkHz42jqdSfTfFQ (OpenAI ads)\ncontext:        58 live Google creatives alongside\nplatform:       Shopify + Cloudflare, theme 162670313687",
             reading="Testing a new ad surface this early is a genuine advantage — most brands in this category have not started. The question to answer next is whether that pixel is tied to the same conversion definition as the Google account."),
        dict(sev="NOTE", title="Technical and security posture is the best in this group",
             evidence="strict-transport-security: max-age=7889238\ncontent-security-policy: block-all-mixed-content; frame-ancestors 'none'\nx-frame-options: DENY\nx-content-type-options: nosniff\ncdn: cloudflare (cf-cache-status DYNAMIC)",
             reading="Headers like these are set by people who care. Measurement discipline, not infrastructure, is where the remaining upside sits."),
        dict(sev="LOW", title="The public rating signal is thin for the level of spend",
             evidence="aggregateRating: 4.4\nrating count:     250\nlive creatives:   ≈58",
             reading="Two hundred and fifty ratings is a small social-proof base for a heritage brand running this much creative. Review volume is usually the cheapest available conversion lever."),
        dict(sev="NOTE", title="Heritage positioning is a real commercial asset",
             evidence="founded: 1988\nheadquarters: Dickenson Road, Bengaluru 560042\npublished: heritage sweet house, now D2C + retail",
             reading="Thirty-eight years of brand equity is not something paid media can buy. The audit's job is to make sure paid traffic converts against that equity rather than diluting it."),
        dict(sev="LOW", title="A single shared inbox carries all published contact",
             evidence="published contact: care@anandsweets.net\nseparate retail, gifting or corporate contacts: none published on the pages reviewed",
             reading="Order queries, corporate gifting enquiries and complaints arriving in one inbox is a routing problem, not a headcount problem. A gifting enquiry is worth many times a cake query."),
    ],
    score_dims=[
        ("Measurement integrity", "OpenAI pixel observed; Google and Meta tag set not fully confirmed.", 3),
        ("Conversion observability", "Conversion definitions across surfaces not verifiable publicly.", 3),
        ("Brand consistency", "Heritage brand, coherent storefront, structured data in place.", 4),
        ("Technical health", "Best header and CDN posture measured in this group.", 4),
        ("Commercial fit", "Festive and gifting demand with fifty-eight live creatives.", 3),
    ],
    grade="A", grade_note="clean foundations; the upside is measurement and social proof, not repair",
    qualification=qual("Anand Sweets has the strongest technical posture in this set, so most findings here are opportunities rather than faults. Google inventory is a live count for one day. Financial and rating figures come from the brand's own published surfaces."),
    next_steps=[
        ("LOW EFFORT · IMMEDIATE BENEFIT", "Confirm the OpenAI pixel fires on the conversion page",
         "It is live in the source. Verifying it fires where an order completes turns an experiment into a measured channel."),
        ("UNDER AN HOUR", "Write one conversion definition for all channels",
         "Google and OpenAI should count the same event, or channel comparisons will not hold."),
        ("HALF A DAY · BIGGEST SINGLE WIN", "Route contact by intent before the festive season",
         "Separate corporate gifting from retail queries. Festive enquiries have the highest ticket size in the calendar and currently share one inbox."),
        ("UNDER AN HOUR", "Ask for reviews at delivery",
         "Two hundred and fifty ratings is thin against fifty-eight live creatives. An automated post-delivery request is a one-time setup."),
        ("LOW EFFORT", "Check the festive creative-to-landing match",
         "Heritage gifting ads should land on a gifting page, not the storefront home."),
    ],
)

# ----------------------------------------------------------------- 4. CHAI POINT
E["chai-point"] = dict(
    brand="Chai Point",
    cover_sub="Paid media and measurement audit. Fifty-six live creatives, one measurement tag observed, and a static site build that publishes its own scale numbers.",
    metrics=[("56", "GOOGLE CREATIVES LIVE"), ("1", "MEASUREMENT TAG OBSERVED"), ("900K+", "CUPS PER DAY (OWN DATA)"), ("6", "FINDINGS IN THIS REPORT")],
    prepared_for_name="The Chai Point growth team",
    prepared_for_line="chaipoint.com  ·  Bengaluru, Karnataka, India",
    prepared_for_link="Prepared from public data only — no ad-account access was requested or used.",
    method=method("chaipoint.com"),
    ad_account_sub="Live paid inventory and measurement surface as measured on the crawl date.",
    ad_account=[
        ("Ad platforms observed", "Google (≈56 creatives, region India) · Meta inventory not measurable on the crawl date"),
        ("Measurement tags", "GA4 G-EN77D2S0YH observed on the site root; Google Ads tag not observed on the root"),
        ("Site platform", "Static build on Amazon S3 behind CloudFront; asset last-modified 22 Sep 2026"),
        ("Design system", "Tailwind v4.3.3; brand #18289c, accent #ff6c22"),
        ("Published scale", "900,000+ cups per day · 150+ stores · 8,100+ workplaces · 9,000+ pincodes (own structured data)"),
        ("Spend · ROAS · CPA", "unavailable (private to the advertiser)"),
        ("Crawl date", CRAWL_DATE),
    ],
    findings=[
        dict(sev="HIGH", title="Only one measurement tag is observable against fifty-six live creatives",
             evidence="ga4:          G-EN77D2S0YH (site root)\ngoogle ads:   not observed on the site root\nmeta pixel:   not observed on the site root\nlive creatives: ≈56 (region India)",
             reading="If the Google Ads tag sits on the ordering sub-domain rather than the marketing root, it would not appear here. Either way, the observable measurement surface is one analytics tag for a business running paid media at scale — worth confirming with a browser check."),
        dict(sev="MEDIUM", title="The site is a static build, so any tag change needs a deploy",
             evidence="host:          Amazon S3 + CloudFront\nlast-modified: 22 Sep 2026 (static assets)\nstack:         Tailwind v4.3.3 front-end",
             reading="Static delivery is fast and cheap, and it is the right call for a store locator. The trade-off is that marketing tags cannot be added by a marketer — every experiment queues behind an engineering release unless a tag manager is present in the build."),
        dict(sev="NOTE", title="The scale story is machine-readable and quotable",
             evidence="json-ld: 900,000+ cups per day\njson-ld: 150+ stores · 8,100+ workplaces · 9,000+ pincodes",
             reading="Structured data this specific is a B2B weapon — workplace and bulk-order demand can be qualified by pincode before a call. Almost no consumer brand in this category publishes it."),
        dict(sev="MEDIUM", title="Bulk and workplace demand is a higher-value channel than the retail creative mix implies",
             evidence="published pages: events and bulk orders\npublished scale:  8,100+ workplaces, 9,000+ pincodes\nlive creatives:   ≈56, predominantly retail coffee",
             reading="Workplace coffee is a contract business with very different economics from a cup. If bulk-order pages were reached by a dedicated campaign, the same spend would face less competition and a longer customer lifetime."),
        dict(sev="LOW", title="Customer care runs through a single published inbox",
             evidence="published contact: customercare@chaipoint.com\nseparate bulk or franchise contact: not published on the pages reviewed",
             reading="Routine queries and B2B enquiries share one address. The B2B enquiry is the one that should never wait in the same queue."),
        dict(sev="NOTE", title="Brand design tokens are applied consistently",
             evidence="brand: #18289c\naccent: #ff6c22\nframework: Tailwind v4.3.3",
             reading="Colour and type are consistent between the site and the published brand system. Creative-to-landing continuity has a solid base to build on."),
    ],
    score_dims=[
        ("Measurement integrity", "One analytics tag observed; ads and pixel tags not visible on the root.", 2),
        ("Conversion observability", "Ordering flow is separate from the marketing root; not confirmed.", 2),
        ("Brand consistency", "Consistent design tokens and published brand system.", 4),
        ("Technical health", "Fast static delivery; tag changes gated behind deploys.", 3),
        ("Commercial fit", "Retail scale plus an untapped contract channel.", 4),
    ],
    grade="B", grade_note="strong operation, under-instrumented marketing surface",
    qualification=qual("Ad inventory is a live count for the brand term on one day. The Meta Ad Library returned only a shell for this brand on the crawl date, so Meta activity is reported as not measurable rather than as zero."),
    next_steps=[
        ("LOW EFFORT · IMMEDIATE BENEFIT", "Run one browser tag check on the ordering flow",
         "Confirm which tags fire on the order page. This decides whether fifty-six creatives are being optimised on real signal."),
        ("UNDER AN HOUR", "Get a tag manager into the static build",
         "Without one, every measurement change waits for a deploy. With one, marketing can iterate independently."),
        ("HALF A DAY · BIGGEST SINGLE WIN", "Put workplace and bulk demand on its own campaign",
         "Eight thousand one hundred workplaces and nine thousand pincodes are already published. A dedicated B2B landing path competes on a quieter auction than retail coffee."),
        ("UNDER AN HOUR", "Separate the bulk enquiry from the support inbox",
         "A routing rule, not a hire. Contract enquiries should never share a queue with cup complaints."),
        ("LOW EFFORT", "Reconcile published store counts with reality each quarter",
         "Structured data that goes stale becomes a credibility risk with enterprise buyers who check it."),
    ],
)

# ----------------------------------------------------------------- 5. THE BAKER'S DOZEN
E["the-baker-s-dozen"] = dict(
    brand="The Baker's Dozen",
    cover_sub="Paid media and measurement audit. Three tag families installed correctly, serving a WordPress site with no cache layer and no security headers.",
    metrics=[("35", "GOOGLE CREATIVES LIVE"), ("3", "TAG FAMILIES DETECTED"), ("0", "SECURITY HEADERS OBSERVED"), ("6", "FINDINGS IN THIS REPORT")],
    prepared_for_name="The Baker's Dozen marketing team",
    prepared_for_line="thebakersdozen.in  ·  Bengaluru, Karnataka, India",
    prepared_for_link="Prepared from public data only — no ad-account access was requested or used.",
    method=method("thebakersdozen.in"),
    ad_account_sub="Live paid inventory and measurement surface as measured on the crawl date.",
    ad_account=[
        ("Ad platforms observed", "Google (≈35 creatives, region India)"),
        ("Measurement tags", "GTM-MQQF2MXB · Google Ads AW-618150299 · Meta pixel 3996239487069441"),
        ("Site platform", "WordPress on nginx"),
        ("Response headers", "strict-transport-security absent · cache-control absent · security headers absent"),
        ("Canonical host", "apex 301 → www"),
        ("Spend · ROAS · CPA", "unavailable (private to the advertiser)"),
        ("Crawl date", CRAWL_DATE),
    ],
    findings=[
        dict(sev="HIGH", title="Well-built tag stack served by a site with no cache layer and no security headers",
             evidence="tags:            GTM-MQQF2MXB · AW-618150299 · pixel 3996239487069441\nstrict-transport-security: absent\ncache-control:   absent\nx-frame-options: absent\nserver:          nginx (WordPress)",
             reading="Measurement is installed the right way — container, ads tag and pixel all present. The infrastructure under it is the weakest part of an otherwise tidy setup, and caching plus four response headers is hours of work."),
        dict(sev="NOTE", title="Tag ordering and coverage look correct",
             evidence="container:   GTM-MQQF2MXB\nads tag:     AW-618150299\nmeta pixel:  3996239487069441",
             reading="All three families are present and independent, which is the pattern you want when paid spend sits across Google and Meta."),
        dict(sev="MEDIUM", title="Thirty-five creatives is enough to learn from and small enough to consolidate quickly",
             evidence="google creatives live: ≈35 (region India)\nads tag present:        AW-618150299",
             reading="At this footprint, a single tidy campaign structure with clean naming will beat more creative volume. The measurement is already in place to prove it."),
        dict(sev="MEDIUM", title="No cache headers means every visit is served cold",
             evidence="cache-control: absent\ncdn:           none observed\nserver:        nginx",
             reading="Adding a cache layer and cache-control headers is a hosting change, not a development project. For a bakery where demand spikes around occasions, cold origin responses are exactly when speed matters most."),
        dict(sev="LOW", title="Security headers are missing across the board",
             evidence="strict-transport-security: absent\nx-frame-options: absent\nx-content-type-options: absent\ncontent-security-policy: absent",
             reading="None of these is exotic. Four directives in the server config close the gap and cost nothing to run."),
        dict(sev="LOW", title="One published inbox covers retail and celebration orders",
             evidence="published contact: fresh@thebakersdozen.in",
             reading="Celebration and bulk orders are the high-ticket path for a bakery. Routing them separately from general enquiries protects the revenue that matters most."),
    ],
    score_dims=[
        ("Measurement integrity", "Container, ads tag and pixel all present and independent.", 3),
        ("Conversion observability", "Tags installed; conversion definitions not verifiable publicly.", 3),
        ("Brand consistency", "Canonical host redirects correctly; brand creative is consistent.", 3),
        ("Technical health", "No cache layer and no security headers on nginx.", 1),
        ("Commercial fit", "Occasion-led demand with thirty-five live creatives.", 3),
    ],
    grade="B", grade_note="measurement is sound; hosting and speed are the drag",
    qualification=qual("Tag detections here come from the site root and are reported as observed values. Google inventory is a live one-day count."),
    next_steps=[
        ("LOW EFFORT · IMMEDIATE BENEFIT", "Add cache-control headers and a cache layer",
         "A hosting change, not a rebuild. It is the single cheapest speed improvement available to this site."),
        ("UNDER AN HOUR", "Set four security headers",
         "HSTS, frame options, content-type options and a basic CSP. One config edit."),
        ("HALF A DAY · BIGGEST SINGLE WIN", "Build one occasion campaign structure",
         "Birthdays, anniversaries and corporate orders have known dates and high ticket sizes. One tidy campaign with clean naming is enough creative at this spend level."),
        ("UNDER AN HOUR", "Route celebration enquiries off the shared inbox",
         "A separate address or form for occasion orders. Free, and it protects the best-margin path."),
        ("LOW EFFORT", "Verify the Meta pixel fires on order completion",
         "The pixel is present. Confirming the event it counts makes Meta reporting comparable with Google."),
    ],
)

# ----------------------------------------------------------------- 6. COTHAS
E["cothas-coffee"] = dict(
    brand="Cothas Coffee",
    cover_sub="Paid media and measurement audit. A 1948 heritage brand with seventy-seven live creatives and a tag layer that could not be confirmed by inspection.",
    metrics=[("77", "GOOGLE CREATIVES LIVE"), ("1948", "FOUNDED"), ("UNCONFIRMED", "TAG LAYER"), ("5", "FINDINGS IN THIS REPORT")],
    prepared_for_name="The Cothas Coffee marketing team",
    prepared_for_line="cothas.com  ·  Jigani, Karnataka 562105",
    prepared_for_link="Prepared from public data only — no ad-account access was requested or used.",
    method=method("cothas.com", [
        "Tag detection on this storefront returned no result from a static source inspection. This is reported as unconfirmed, not as absent, because Shopify themes commonly inject tags through app scripts a static fetch cannot execute.",
    ]),
    ad_account_sub="Live paid inventory and measurement surface as measured on the crawl date.",
    ad_account=[
        ("Ad platforms observed", "Google (≈77 creatives, region India)"),
        ("Measurement tags", "unconfirmed — selectors for tag manager and pixel returned no result on the crawls attempted"),
        ("Site platform", "Shopify"),
        ("Published contact", "customercare@cothas.com"),
        ("Brand heritage", "founded 1948; facility at Jigani, Karnataka 562105"),
        ("Spend · ROAS · CPA", "unavailable (private to the advertiser)"),
        ("Crawl date", CRAWL_DATE),
    ],
    findings=[
        dict(sev="HIGH", title="Seventy-seven live creatives run against an unconfirmed tag layer",
             evidence="google creatives live: 77 (region India)\ntag inspection:        no tag-manager or pixel selector resolved\nsite platform:         Shopify\nconfidence:            single method — not asserted as absence",
             reading="Either the tags are injected in a way a static fetch cannot see, or paid traffic is landing on a storefront whose conversion signal is thinner than the spend implies. A browser-based check with a tag assistant settles it in minutes, and it is the first thing to do."),
        dict(sev="NOTE", title="Heritage is the brand's sharpest asset",
             evidence="founded:  1948\nfacility:  Jigani, Karnataka 562105\ncategory:  filter coffee, South Indian household staple",
             reading="Seventy-eight years of household familiarity is rare in this market. The storefront is modern; the paid strategy should be playing the heritage card harder than it appears to be."),
        dict(sev="MEDIUM", title="A modern storefront on a heritage brand without a confirmed measurement layer",
             evidence="platform: Shopify\ncontact:  customercare@cothas.com",
             reading="A Shopify storefront is the easiest platform in this set on which to install measurement — the tags are usually a two-minute app install. That makes the unconfirmed result more surprising, not less."),
        dict(sev="LOW", title="One shared inbox for retail, trade and complaints",
             evidence="published contact: customercare@cothas.com\nseparate wholesale contact: none published on the pages reviewed",
             reading="Filter coffee has a strong HoReCa and wholesale channel. Trade enquiries should not queue behind retail complaints."),
        dict(sev="MEDIUM", title="Subscription and repeat-purchase mechanics are the natural fit for this category",
             evidence="category: filter coffee, daily household consumption\ninventory: 77 live creatives\ntag layer: unconfirmed",
             reading="Daily-consumption categories live or die on repeat rate. Without a confirmed tag layer, repeat behaviour cannot be measured or retargeted — which is where the 77 creatives should be pointed."),
    ],
    score_dims=[
        ("Measurement integrity", "Tag layer unconfirmed by the methods used.", 1),
        ("Conversion observability", "Unknown until the browser check is run.", 2),
        ("Brand consistency", "Strong heritage identity, modern storefront.", 3),
        ("Technical health", "Standard Shopify stack; no defects observed.", 3),
        ("Commercial fit", "Daily-consumption category with seventy-seven live creatives.", 3),
    ],
    grade="C", grade_note="live paid spend with an unverified measurement path",
    qualification=qual("No tag absence is claimed anywhere in this report. Where a selector returned nothing, the result is reported as unconfirmed and the method is named. Google inventory is a live one-day count."),
    next_steps=[
        ("LOW EFFORT · IMMEDIATE BENEFIT", "Spend ten minutes with a tag assistant on the storefront",
         "Confirm which tags fire on the home page, the product page and checkout. Everything else in this report builds on that answer."),
        ("UNDER AN HOUR", "Install or verify the Shopify measurement apps",
         "On this platform the tags are usually a two-minute install. There is no engineering reason for the gap."),
        ("HALF A DAY · BIGGEST SINGLE WIN", "Build a repeat-purchase audience",
         "Filter coffee is a daily habit. A subscription offer plus a retargeting audience of past buyers is the highest-value use of seventy-seven creatives."),
        ("UNDER AN HOUR", "Route wholesale enquiries away from the support inbox",
         "HoReCa and trade buyers should have their own path. It costs nothing and it is measurable."),
        ("LOW EFFORT", "Confirm the Google Ads tag count events once, not twice",
         "Duplicate counting inflates reported conversions and is common on Shopify installs."),
    ],
)

# ----------------------------------------------------------------- 7. EARLY FOODS
E["early-foods"] = dict(
    brand="Early Foods",
    cover_sub="Paid media and measurement audit. Thirty live creatives on a managed Shopify stack, with the measurement surface unverified from outside.",
    metrics=[("30", "GOOGLE CREATIVES LIVE"), ("SHOPIFY", "PLATFORM"), ("CLOUDFLARE", "CDN OBSERVED"), ("4", "FINDINGS IN THIS REPORT")],
    prepared_for_name="The Early Foods growth team",
    prepared_for_line="earlyfoods.com  ·  India (D2C, shipped nationally)",
    prepared_for_link="Prepared from public data only — no ad-account access was requested or used.",
    method=method("earlyfoods.com"),
    ad_account_sub="Live paid inventory and measurement surface as measured on the crawl date.",
    ad_account=[
        ("Ad platforms observed", "Google (≈30 creatives, region India)"),
        ("Measurement tags", "not measured on this crawl — reported as unavailable"),
        ("Site platform", "Shopify behind Cloudflare; theme 124761112618"),
        ("Published contact", "hello@earlyfoods.com"),
        ("Spend · ROAS · CPA", "unavailable (private to the advertiser)"),
        ("Crawl date", CRAWL_DATE),
    ],
    findings=[
        dict(sev="MEDIUM", title="Thirty live creatives on a storefront whose measurement surface was not verified",
             evidence="google creatives live: ≈30 (region India)\nplatform:              Shopify + Cloudflare, theme 124761112618\ntag measurement:       not performed on this crawl — unavailable",
             reading="The inventory is small enough that a single measurement error costs real money proportionally. Verifying the tag layer is the first task, and the platform makes it easy."),
        dict(sev="NOTE", title="The storefront runs on a fully managed stack",
             evidence="platform: Shopify\ntheme:    124761112618\ncdn:      Cloudflare (cf-cache-status observed)",
             reading="Managed hosting removes whole categories of technical risk. There is nothing structurally wrong to fix here — the question is purely whether the paid signal is complete."),
        dict(sev="LOW", title="A single inbox carries the published contact path",
             evidence="published contact: hello@earlyfoods.com",
             reading="For a young brand, one inbox is a reasonable choice at low volume. It becomes a bottleneck at exactly the moment paid media starts working, so plan the split before it is urgent."),
        dict(sev="MEDIUM", title="Category fit is strong but conversion depends on trust signals",
             evidence="category: early-years and child nutrition\ncontact:  hello@earlyfoods.com",
             reading="Parents do not buy child nutrition from an ad alone — they buy from a brand that looks accountable. Reviews, ingredient sourcing and a visible support path are the conversion levers that make the same thirty creatives perform better."),
    ],
    score_dims=[
        ("Measurement integrity", "Tag layer not measured on this crawl.", 2),
        ("Conversion observability", "Not verified publicly.", 2),
        ("Brand consistency", "Clean managed storefront with a consistent theme.", 3),
        ("Technical health", "Cloudflare plus Shopify; no defects observed.", 3),
        ("Commercial fit", "Trust-driven category where paid spend can compound.", 3),
    ],
    grade="B", grade_note="clean platform, unverified measurement",
    qualification=qual("This report deliberately reports the tag layer as unavailable rather than guessing. Only the platform, CDN, contact and live ad count were measured."),
    next_steps=[
        ("LOW EFFORT · IMMEDIATE BENEFIT", "Run a tag check on the product and checkout pages",
         "Confirm the pixel and the Google Ads tag both fire where an order completes."),
        ("UNDER AN HOUR", "Write down one conversion definition",
         "First order, repeat order and subscription should be counted separately, or the algorithm will optimise for the cheapest action available."),
        ("HALF A DAY · BIGGEST SINGLE WIN", "Build a parent-trust landing page for the top creatives",
         "Ingredient sourcing, safety testing and reviews, in one page. It improves the same creative rather than asking for more spend."),
        ("UNDER AN HOUR", "Set up a post-purchase review request",
         "Rating volume is the cheapest conversion asset in a trust category."),
    ],
)

# ----------------------------------------------------------------- 8. iD FRESH
E["id-fresh-food"] = dict(
    brand="iD Fresh Food",
    cover_sub="Paid media and measurement audit. A profitable Rs 681 Cr business running a single live Google creative on a self-hosted WordPress site.",
    metrics=[("1", "GOOGLE CREATIVE LIVE"), ("Rs 681.4 Cr", "PUBLISHED FY25 REVENUE"), ("Rs 25.87 Cr", "PUBLISHED FY25 PAT"), ("5", "FINDINGS IN THIS REPORT")],
    prepared_for_name="The iD Fresh marketing team",
    prepared_for_line="idfreshfood.com  ·  Bengaluru, Karnataka, India",
    prepared_for_link="Prepared from public data only — no ad-account access was requested or used.",
    method=method("idfreshfood.com", [
        "Published financial figures are from the company's FY25 results as reported publicly; they were not audited by us.",
    ]),
    ad_account_sub="Live paid inventory and measurement surface as measured on the crawl date.",
    ad_account=[
        ("Ad platforms observed", "Google (1 creative live, region India)"),
        ("Site platform", "WordPress on LiteSpeed; cache HIT observed"),
        ("Response headers", "access-control-allow-origin: * · content-security-policy: report-only"),
        ("Published contact", "customercare@idfreshfood.com"),
        ("Published FY25", "revenue approx Rs 681.4 Cr · profit after tax approx Rs 25.87 Cr"),
        ("Spend · ROAS · CPA", "unavailable (private to the advertiser)"),
        ("Crawl date", CRAWL_DATE),
    ],
    findings=[
        dict(sev="HIGH", title="One live Google creative against a Rs 681 Cr revenue base",
             evidence="google creatives live: 1 (region India)\npublished FY25:         revenue approx Rs 681.4 Cr · PAT approx Rs 25.87 Cr\nplatform:               WordPress + LiteSpeed",
             reading="A profitable business at this scale with a single live Google creative is not under-spending — it is under-testing. There is no channel data to learn from at one creative, and the first three to five test cells are where the learning is."),
        dict(sev="HIGH", title="Wildcard CORS is switched on for the whole site",
             evidence="access-control-allow-origin: *\ncontent-security-policy: report-only",
             reading="A wildcard origin lets any site call the domain's resources. For a brand with a logged-in or form-based surface this is a security setting, not a performance one, and it is a single line in the server config."),
        dict(sev="MEDIUM", title="Content-security-policy is report-only, so it enforces nothing",
             evidence="content-security-policy: report-only\ncache: LiteSpeed cache HIT (working correctly)",
             reading="Report-only mode is the right way to roll a policy out, and it is the wrong place to stop. The cache layer is doing its job; the security policy is not yet doing anything."),
        dict(sev="NOTE", title="Hosting is well configured for speed",
             evidence="server stack: WordPress on LiteSpeed\ncache status:  HIT\nimplication:   full-page cache serving correctly",
             reading="LiteSpeed with a cache hit is a fast, cheap configuration — better than most of this group. The technical platform is not the constraint here."),
        dict(sev="LOW", title="A single support inbox carries all published contact",
             evidence="published contact: customercare@idfreshfood.com",
             reading="With modern trade, HoReCa and D2C running side by side, one public address under-serves the highest-value partner conversations."),
    ],
    score_dims=[
        ("Measurement integrity", "No tag set confirmed; only platform and headers measured.", 2),
        ("Conversion observability", "One live creative means little to observe.", 2),
        ("Brand consistency", "Established brand, self-hosted site, consistent identity.", 3),
        ("Technical health", "Fast LiteSpeed cache, but wildcard CORS and report-only CSP.", 2),
        ("Commercial fit", "Profitable at scale with almost no paid testing.", 2),
    ],
    grade="C", grade_note="a strong business leaving paid learning on the table",
    qualification=qual("Revenue and profit figures are published FY25 results as reported, not figures we audited. The single-creative count is a live count for the brand term on one day."),
    next_steps=[
        ("LOW EFFORT · IMMEDIATE BENEFIT", "Replace the wildcard CORS setting",
         "One server line. It is the only security finding in an otherwise well-run stack."),
        ("UNDER AN HOUR", "Promote the security policy from report-only to enforced",
         "After a week of clean reports, turn it on. It is a config change, not a project."),
        ("HALF A DAY · BIGGEST SINGLE WIN", "Run a five-cell creative test",
         "One live creative teaches nothing. Five cells across two propositions and three audiences is the minimum viable test for a business this size."),
        ("UNDER AN HOUR", "Give HoReCa and modern trade separate contact paths",
         "The highest-value conversations should not share an inbox with retail complaints."),
        ("LOW EFFORT", "Confirm the conversion tag before scaling creative",
         "More creative without a confirmed conversion event just multiplies noise."),
    ],
)

# ----------------------------------------------------------------- 9. THIRD WAVE COFFEE
E["third-wave-coffee"] = dict(
    brand="Third Wave Coffee",
    cover_sub="Paid media and measurement audit. A strong offline brand whose website title tag still reads as its own domain name, with no live Google creative found.",
    metrics=[("0", "GOOGLE CREATIVES FOUND"), ("1", "TITLE TAG DEFECT"), ("SHOPIFY", "PLATFORM"), ("5", "FINDINGS IN THIS REPORT")],
    prepared_for_name="The Third Wave Coffee growth team",
    prepared_for_line="thirdwavecoffeeroasters.com  ·  Bengaluru, Karnataka, India",
    prepared_for_link="Prepared from public data only — no ad-account access was requested or used.",
    method=method("thirdwavecoffeeroasters.com"),
    ad_account_sub="Live paid inventory and measurement surface as measured on the crawl date.",
    ad_account=[
        ("Ad platforms observed", "Google — no live creative found for the brand term in the India region on the crawl date"),
        ("Site platform", "Shopify behind Cloudflare; theme 133405212742"),
        ("Title tag observed", "www.thirdwavecoffeeroasters.com — the domain string, not the brand name"),
        ("Published contact", "orders@thirdwavecoffee.in"),
        ("Canonical host", "apex 301 → www"),
        ("Spend · ROAS · CPA", "unavailable (private to the advertiser)"),
        ("Crawl date", CRAWL_DATE),
    ],
    findings=[
        dict(sev="HIGH", title="The homepage title tag is the domain string rather than the brand name",
             evidence="title tag:  www.thirdwavecoffeeroasters.com\nplatform:   Shopify + Cloudflare, theme 133405212742",
             reading="The title tag is what appears in the browser tab, in search results and in shared links. A domain string there wastes every impression the brand earns, and it is a two-minute theme edit."),
        dict(sev="HIGH", title="No live Google creative was found for the brand term",
             evidence="google ads transparency: 0 creatives (region India, brand term)\ncompetitors in this set:   1 to 400 creatives live",
             reading="A brand with this much physical presence does not need to buy search for its own name, but the absence of any live inventory means there is no paid surface at all for new-city or new-product demand. That is a choice worth making explicitly."),
        dict(sev="MEDIUM", title="The storefront is otherwise well built",
             evidence="platform: Shopify behind Cloudflare\ntheme:    133405212742\ncanonical host: apex 301 → www",
             reading="The stack is standard and the redirect is clean. The visible gap is presentation and paid presence, not engineering."),
        dict(sev="MEDIUM", title="Contact is a single orders address",
             evidence="published contact: orders@thirdwavecoffee.in",
             reading="Cafes, online orders, franchise enquiries and events are different businesses. One address for all of them loses the enquiry that is worth the most."),
        dict(sev="NOTE", title="The physical brand is stronger than the digital surface implies",
             evidence="category: specialty coffee, Bengaluru\nplatform: Shopify storefront\npaid inventory: none found on the crawl date",
             reading="Cafe footfall and specialty positioning are real assets. The website and the paid surface are not yet carrying that equity — which is an opportunity, not a criticism."),
    ],
    score_dims=[
        ("Measurement integrity", "No tag set confirmed; platform measured only.", 2),
        ("Conversion observability", "No live paid surface to observe.", 2),
        ("Brand consistency", "Title tag contradicts the brand on the homepage.", 1),
        ("Technical health", "Standard Shopify behind Cloudflare; redirect correct.", 3),
        ("Commercial fit", "Strong offline brand with an under-built digital surface.", 2),
    ],
    grade="C", grade_note="a strong brand leaving its digital front door unfinished",
    qualification=qual("The Google result is reported exactly as measured: no live creative found for the brand term on one day. Paid campaigns may exist under other terms or advertiser names, which a public search cannot reveal."),
    next_steps=[
        ("LOW EFFORT · IMMEDIATE BENEFIT", "Fix the homepage title tag",
         "Replace the domain string with the brand name and what it sells. Two minutes, affects every search result and shared link."),
        ("UNDER AN HOUR", "Split the contact addresses by intent",
         "Orders, franchise and events each deserve their own path."),
        ("HALF A DAY · BIGGEST SINGLE WIN", "Decide whether paid inventory should exist at all",
         "If the answer is yes, start with new-customer acquisition in the two or three cities where cafes are opening. If no, make it a documented decision rather than an omission."),
        ("UNDER AN HOUR", "Confirm measurement before any spend starts",
         "Shopify makes this a quick install. Starting paid without it wastes the first month."),
        ("LOW EFFORT", "Align the storefront's look with the cafe experience",
         "The physical brand is premium; the storefront should not look like a stock theme."),
    ],
)

# ----------------------------------------------------------------- 10. FROZEN BOTTLE
E["frozen-bottle"] = dict(
    brand="Frozen Bottle",
    cover_sub="Paid media and measurement audit. Eleven live creatives pointing at a storefront with a broken FAQ page.",
    metrics=[("11", "GOOGLE CREATIVES LIVE"), ("1", "STALE URL VARIANT"), ("SHOPIFY", "PLATFORM"), ("5", "FINDINGS IN THIS REPORT")],
    prepared_for_name="The Frozen Bottle growth team",
    prepared_for_line="frozenbottle.com  ·  Bengaluru, Karnataka, India",
    prepared_for_link="Prepared from public data only — no ad-account access was requested or used.",
    method=method("frozenbottle.com"),
    ad_account_sub="Live paid inventory and measurement surface as measured on the crawl date.",
    ad_account=[
        ("Ad platforms observed", "Google (≈11 creatives, region India)"),
        ("Site platform", "Shopify behind Cloudflare; theme 175376138404"),
        ("Stale URL observed", "frozenbottle.com/pages/faq returns HTTP 404; the live FAQ is at /pages/faqs (plural) and works"),
        ("Published contact", "vipul@frozenbottle.in"),
        ("Franchise page", "published franchise page present on the storefront"),
        ("Spend · ROAS · CPA", "unavailable (private to the advertiser)"),
        ("Crawl date", CRAWL_DATE),
    ],
    findings=[
        dict(sev="LOW", title="A stale FAQ URL returns 404, and the 404 template still shows placeholder products",
             evidence="url:           frozenbottle.com/pages/faq → HTTP 404\nlive FAQ:      frozenbottle.com/pages/faqs (plural) works\n404 template:  'Example product $29' cards still render\nhomepage:      links only to the working plural URL",
             reading="The live FAQ is reachable, so no customer is blocked today. What remains is a stale URL that should redirect to the working one, and a 404 template still showing unconfigured Shopify placeholder cards. Both are minutes of theme work, and both are visible the moment a paid visitor mistypes a link."),
        dict(sev="MEDIUM", title="Eleven live creatives is below the learning threshold for this category",
             evidence="google creatives live: ≈11 (region India)\ncategory:              desserts, ice cream and gifting",
             reading="Eleven creatives across any meaningful audience set will not separate creative from audience effects. Two clean tests would tell more than eleven undifferentiated ads."),
        dict(sev="NOTE", title="Franchise demand has a published path",
             evidence="published: franchise page on the storefront\ncontact:   vipul@frozenbottle.in",
             reading="A public franchise page is a growth channel in itself — franchise enquiries have a very different value from dessert orders and should be measured separately."),
        dict(sev="LOW", title="One published contact for orders and franchise enquiries",
             evidence="published contact: vipul@frozenbottle.in",
             reading="Franchise enquiries and customer orders in one place makes neither measurable."),
        dict(sev="NOTE", title="Platform hygiene is otherwise standard and safe",
             evidence="platform: Shopify + Cloudflare\ntheme:    175376138404",
             reading="There is nothing structurally wrong with the site. The fixes in this report are content and configuration, not architecture."),
    ],
    score_dims=[
        ("Measurement integrity", "Tag set not confirmed on the crawl.", 2),
        ("Conversion observability", "Small live footprint; a stale FAQ URL and an unconfigured 404 template.", 3),
        ("Brand consistency", "Storefront consistent with the brand identity.", 3),
        ("Technical health", "Standard Shopify stack; stale URL variant and placeholder 404 template.", 2),
        ("Commercial fit", "Dessert and gifting demand with a franchise channel.", 2),
    ],
    grade="C", grade_note="small fixes standing between spend and conversions",
    qualification=qual("The 404 was measured directly on the crawl date. Ad counts are live one-day counts."),
    next_steps=[
        ("LOW EFFORT · IMMEDIATE BENEFIT", "Redirect the stale FAQ URL to the live one",
         "Point /pages/faq at /pages/faqs and clear the placeholder product cards from the 404 template. Minutes of theme work; it removes the only rough edge a paid visitor can hit."),
        ("UNDER AN HOUR", "Split franchise enquiries from customer support",
         "Franchise is a different business with a different value. Give it its own path."),
        ("HALF A DAY · BIGGEST SINGLE WIN", "Run two clean creative tests",
         "Two propositions, two audiences. Eleven undifferentiated creatives teach less than four organised cells."),
        ("UNDER AN HOUR", "Confirm the pixel fires before scaling dessert season creative",
         "Seasonality is the whole category. Measurement should be ready before the peak."),
        ("LOW EFFORT", "Add delivery-area clarity above the fold",
         "In quick commerce categories, serviceable pincode is the first question a buyer has."),
    ],
)

# ----------------------------------------------------------------- 11. MILKY MIST
E["milky-mist"] = dict(
    brand="Milky Mist",
    cover_sub="Paid media and measurement audit. Three live creatives on a Wix storefront for a dairy brand with national retail distribution.",
    metrics=[("3", "GOOGLE CREATIVES LIVE"), ("WIX", "PLATFORM"), ("1", "CDN VENDOR OBSERVED"), ("4", "FINDINGS IN THIS REPORT")],
    prepared_for_name="The Milky Mist marketing team",
    prepared_for_line="milkymist.com  ·  Erode and Bengaluru, India",
    prepared_for_link="Prepared from public data only — no ad-account access was requested or used.",
    method=method("milkymist.com"),
    ad_account_sub="Live paid inventory and measurement surface as measured on the crawl date.",
    ad_account=[
        ("Ad platforms observed", "Google (≈3 creatives, region India)"),
        ("Site platform", "Wix behind Varnish (x-wix-request-id observed)"),
        ("Published contact", "customercare@milkymist.com"),
        ("Canonical host", "apex 301 → www"),
        ("Spend · ROAS · CPA", "unavailable (private to the advertiser)"),
        ("Crawl date", CRAWL_DATE),
    ],
    findings=[
        dict(sev="HIGH", title="Three live creatives for a dairy brand with national retail distribution",
             evidence="google creatives live: 3 (region India)\ncomparison in this set: one competitor runs ≈400\nplatform:              Wix behind Varnish",
             reading="Retail distribution and paid demand are two different engines. Three creatives cannot generate pull for a brand that is already on shelves — the first task is deciding which products to put paid behind."),
        dict(sev="MEDIUM", title="The site runs on a site-builder stack rather than a commerce stack",
             evidence="platform: Wix\nserving layer: Varnish\ncontact: customercare@milkymist.com",
             reading="Wix is fast to launch and hard to instrument precisely. If direct-to-consumer is a real ambition, the measurement and checkout stack — not the design — is the constraint to plan around."),
        dict(sev="MEDIUM", title="The contact path is a single support inbox",
             evidence="published contact: customercare@milkymist.com\nseparate distributor or trade contact: not published on the pages reviewed",
             reading="For a brand in retail, distributor and trade enquiries are the highest-value inbound. They should be separable from consumer complaints on day one."),
        dict(sev="LOW", title="Canonical host handling is correct",
             evidence="milkymist.com → 301 → www.milkymist.com",
             reading="One fewer thing to fix. Paid and organic traffic land on a single host."),
    ],
    score_dims=[
        ("Measurement integrity", "Tag set not confirmed on the crawl.", 2),
        ("Conversion observability", "Small paid footprint; D2C path not verified.", 2),
        ("Brand consistency", "Established retail brand, consistent identity.", 3),
        ("Technical health", "Managed platform; no defects observed.", 3),
        ("Commercial fit", "Large retail base with almost no paid demand generation.", 2),
    ],
    grade="C", grade_note="brand strength ahead of its paid and measured presence",
    qualification=qual("Ad counts are live one-day counts for the brand term. The tag layer was not measured for this brand and is reported as unavailable rather than assumed."),
    next_steps=[
        ("LOW EFFORT · IMMEDIATE BENEFIT", "Choose the three products paid media should push",
         "Premium dairy wins on specific products, not the whole catalogue. Three creatives should map to three products."),
        ("UNDER AN HOUR", "Separate distributor enquiries from consumer support",
         "The highest-value inbound should not share an inbox with complaints."),
        ("HALF A DAY · BIGGEST SINGLE WIN", "Test a subscription offer for daily dairy",
         "Daily consumption is the category's structural advantage. A subscription test is the most valuable use of a small budget."),
        ("UNDER AN HOUR", "Confirm what can be measured on this platform before spending more",
         "Site-builder stacks vary in what they expose. Knowing the ceiling prevents surprises later."),
    ],
)
