# -*- coding: utf-8 -*-
"""Food / Bangalore audit leads - Part A (all data verified live on 02 Oct 2026)."""

VERIFIED = "02 OCT 2026"

LEADS_A = [
# ---------------------------------------------------------------- LICIOUS
{
 "brand": "Licious",
 "website": "licious.in",
 "instagram": "@licious_foods",
 "contact": {"email": "talktous@licious.com", "phone": "1800-4190-786", "entity": "Delightful Gourmet Pvt Ltd", "address": "Maruti Infotech Center, Amarjyothi Layout, Domlur, Bengaluru 560071"},
 "niche": "D2C Meat & Seafood",
 "score": 7,
 "ads_active": 300,
 "headline": "INR 795 Cr revenue - and paid clicks land on a store-locator. That single step is the leak.",
 "stats": [("~300", "Google creatives live"), ("Paid live", "Meta + Google"), ("INR 795 Cr", "FY25 revenue"), ("Bengaluru", "Core market")],
 "ad_intro": "Licious runs one of the largest paid footprints we have audited in Indian food D2C: ~300 live Google Ads creatives under Delightful Gourmet Pvt Ltd, plus a Meta presence we verified live (Library ID 983369480870934, running since 15 Apr 2026). The product story is excellent - 'caught in small boats', 'never frozen', '0-4C from source to store'. The gap is where the money lands: the live Bengaluru Meta ad routes traffic to licious.in/store-locator, and Google spend is spread across a very wide creative base - while FY25 closed at INR 795 Cr revenue with a INR 218.3 Cr net loss. The three fixes below make the existing spend convert harder; they do not ask for a bigger budget.",
 "ad_intelligence": [
   ["Google Ads (verified)", "~300 live creatives under Delightful Gourmet Pvt Ltd - brand, category and Local store ads (we captured e.g. 'Licious Neo Town Electronic City' store-level ads)."],
   ["Meta / Facebook (verified live)", "Active ads confirmed in Meta Ad Library - Library ID 983369480870934, first seen 15 Apr 2026. This is a sustained flight, not a test."],
   ["Meta copy angle", "Cold-chain trust stack: 'Your favourite Fish & Seafood', 'Caught in small boats', 'No added chemicals', 'Never frozen', 'Maintained at 0-4C from source to store' - plus a Kannada-language hook for Bengaluru."],
   ["Live destination", "licious.in/store-locator?city_name=Bengaluru&city_id=1 - the click lands on a city/store picker, one full step before any product or price."],
   ["Market context", "FY25 revenue INR 795 Cr, net loss INR 218.3 Cr; ~USD 490M raised; IPO reportedly deferred to FY27-28. Efficiency is the board-level conversation right now."],
 ],
 "scores": {
   "Creative Variety": [7, "#F59E0B"],
   "UGC & Social Proof": [5, "#F59E0B"],
   "Copy & Hook Strength": [8, "#10B981"],
   "Landing Page CRO": [4, "#EF4444"],
   "Tracking & CAPI": [6, "#F59E0B"],
   "Retargeting Depth": [6, "#F59E0B"],
 },
 "findings": [
   "<b>Destination leak (highest cost):</b> the verified live Meta ad for Bengaluru sends clicks to the store-locator. Every extra step between ad and cart costs conversion - and this is the single most expensive step you can add to a food ad, because freshness intent decays in seconds. Fix: deep-link to the SKU page with city pre-selected, keep the locator as a secondary link.",
   "<b>Spend spread:</b> ~300 creatives including a large agency-run Local store-ad layer (Freeflow is not the buyer here - Delightful Gourmet is the verified advertiser). With this volume, budget is being thinned across many assets and geos instead of concentrated on the SKU/geo clusters that carry the cold-chain promise best.",
   "<b>Promise not carried into the landing:</b> 'Never frozen' and '0-4C' are your strongest assets - they should be the hero of the destination page, not just the ad. The locator page does not carry them.",
   "<b>Measurement risk:</b> with Meta + Google + Local store ads running together, if CAPI / Enhanced Conversions are not clean, Smart Bidding optimises on partial signal - you pay more per order without a visible reason.",
 ],
 "competitors": [
   ["FreshtoHome / Zappfresh", "Category landing pages with same-day delivery proof above the fold.", "Deep-link ad traffic to category pages (fish / chicken / mutton) with delivery-slot proof, not a locator."],
   ["Country Delight (adjacent subscription model)", "Subscription-first funnel; retention mechanics pull users back weekly.", "Licious already offers subscription - surface it inside the ad landing path and in retargeting."],
   ["Quick-commerce meat counters", "Set a 10-minute delivery expectation inside the app.", "Do not fight on speed. Win on cold-chain trust and source story - make that the landing hero."],
 ],
 "wins": [
   ["WIN 1 - CRO: Route meta clicks to the product page, not the locator", "Rewrite the 5 highest-spend Bengaluru Meta ads to land on the SKU page with city_id=1 pre-set and the locator as a secondary CTA. Keep UTMs identical so the comparison stays clean for 14 days.", "#EF4444", "#FEF2F2"],
   ["WIN 2 - Creative: Systemise the cold-chain proof", "Take the assets that already work ('small boats', 'never frozen') and build a repeatable 3-format system: 15s cold-chain proof Reel, 15s source-story Reel, 15s offer card. Refresh weekly from one shoot day instead of ad-hoc creatives.", "#F59E0B", "#FFFBEB"],
   ["WIN 3 - Tracking: Meta CAPI + Enhanced Conversions", "Audit server-side events end to end, dedupe browser/server, and pass order value. If Smart Bidding sees full signal, the same spend buys more carts - before any creative change.", "#10B981", "#ECFDF5"],
 ],
 "impact": [
   ["Metric", "Current (live)", "After Wins (est.)", "Impact"],
   ["Ad-to-cart steps", "Ad -> store-locator -> product", "Ad -> product page (city preset)", "Removes the costliest drop-off"],
   ["Landing conversion", "Trust hooks proven, weak destination", "Same hooks, product-page destination", "+20-35% conversion on same spend"],
   ["Creative refresh rate", "High volume, ad-hoc", "Weekly 3-format system", "Lower fatigue, lower CPA"],
   ["Signal quality", "Multi-channel, unclear dedupe", "Clean CAPI + Enhanced Conversions", "Better Smart Bidding efficiency"],
 ],
 "sources": [
   "Google Ads Transparency (region IN): ~300 live creatives under Delightful Gourmet Pvt Ltd, incl. Local store ads (re-verified 02 Oct 2026).",
   "Meta Ad Library: Library ID 983369480870934 live since 15 Apr 2026; destination licious.in/store-locator (Bengaluru) verified.",
   "licious.in: contact + store-locator pages (talktous@licious.com, 1800-4190-786, Domlur, Bengaluru 560071).",
   "Public FY25 results coverage: revenue INR 795 Cr, net loss INR 218.3 Cr; funding ~USD 490M; IPO timing reported.",
 ],
 "outreach": [
  ["Email 1 (Day 1): Your Bengaluru Meta ad lands on a store-locator - here is the audit",
   "Hi team,<br/><br/>I run paid-media audits for food brands out of Bengaluru. Over the last few days I inspected your live ad footprint - not a guess: Google Ads Transparency shows <b>~300 creatives</b> under Delightful Gourmet Pvt Ltd, and I verified your Meta flight live in the Ad Library (Library ID 983369480870934, running since 15 Apr 2026).<br/><br/>One finding you can act on today: that live Meta ad sends Bengaluru clicks to <b>licious.in/store-locator</b>. Buyers who tapped because of 'never frozen' arrive at a city picker - one full step before they see a product or price.<br/><br/>I have attached the 7-page Paid Media and Measurement Audit, all doable without increasing spend. Worth 15 minutes?<br/><br/>- Smart Pursuit, Bengaluru | 7095024220<br/><br/>P.S. The 0-4C cold-chain story is genuinely your strongest asset. It deserves to be the hero of the landing page, not just the ad."],
  ["Email 2 (Day 3): The cheapest fix in the Licious audit",
   "Hi team,<br/><br/>Following up on the audit. If you only do one thing this week: take your 5 biggest-spend Bengaluru Meta ads and repoint them from the store-locator to the SKU page with city_id=1 pre-set.<br/><br/>It needs no new creative, no new budget - and it removes the single most expensive step between the tap and the cart. Keep the locator as the secondary CTA.<br/><br/>Happy to send the exact URL pattern and the UTM setup we use so your comparison stays clean for 14 days.<br/><br/>- Smart Pursuit | 7095024220"],
  ["Email 3 (Day 7): Why your Google spend is thinning out",
   "Hi team,<br/><br/>Second observation from the audit: with ~300 Google creatives live - including a large Local store-ad layer - budget gets spread thinly across assets and geos. Concentrating spend on the SKU/geo clusters that match your cold-chain promise typically beats adding creatives.<br/><br/>We build this exact consolidation + creative-refresh system for food brands: one shoot day a week, three formats, weekly rotation. Your 'small boats' and 'never frozen' angles already do the heavy lifting - they just need a system behind them.<br/><br/>I can walk you through the model in 15 minutes.<br/><br/>- Smart Pursuit | 7095024220"],
  ["Email 4 (Day 14): Closing the file on Licious",
   "Hi team,<br/><br/>Last note from me. The audit attached on Day 1 is yours to keep - the three fixes are: (1) deep-link Meta clicks to product pages, (2) concentrate Google spend on top SKU/geo clusters, (3) audit CAPI + Enhanced Conversions so Smart Bidding sees full signal.<br/><br/>If the timing is wrong, no problem - the file stays accurate for roughly a quarter. If you want us to implement any of it, we can start with the tracking audit this week.<br/><br/>- Smart Pursuit | 7095024220"],
 ],
 "verified_on": VERIFIED,
},
# ---------------------------------------------------------------- COTHAS
{
 "brand": "Cothas Coffee",
 "website": "cothas.com",
 "instagram": "@cothascoffee",
 "contact": {"email": "customercare@cothas.com", "phone": "", "entity": "Cothas Coffee Co.", "address": "Jigani Industrial Area, Anekal Taluk, Bengaluru 562105"},
 "niche": "Coffee Roasting & Vending",
 "score": 7,
 "ads_active": 77,
 "headline": "A 1948 coffee house running 77 Google ads - through an agency, with no local landing pages.",
 "stats": [("77", "Google creatives live"), ("Since 1948", "Brand heritage"), ("Agency-run", "Freeflow Creative Services"), ("Bengaluru", "Home market")],
 "ad_intro": "Cothas is one of the few legacy Bengaluru coffee brands actually investing in paid media: 77 live Google Ads creatives, verified under Freeflow Creative Services India Pvt Ltd - i.e. the account is agency-managed. The inventory includes Local store ads (we captured 'Cothas Coffee HMT Road Mathikere'), which is exactly the right instinct for a brand whose growth now runs on vending machines, CoCo outlets and e-commerce. The leak is that the paid clicks land on a general site while the strongest demand signals - 'coffee vending machine', 'CoCo outlet near me', 'filter coffee subscription' - deserve their own destination pages.",
 "ad_intelligence": [
   ["Google Ads (verified)", "77 live creatives; advertiser of record is Freeflow Creative Services India Pvt Ltd (agency-managed account)."],
   ["Local store ads", "Confirmed - e.g. 'Cothas Coffee HMT Road Mathikere'. Store-level ads are live, which is rare for a legacy F&B brand."],
   ["Brand system", "Brand red #cb0024 carried consistently across site; Google Tag Manager GTM-K6SZV8J installed; site runs a modern stack on cothas.com."],
   ["Product lines in play", "Filter coffee / instant / vending machines / CoCo outlets / snacks - a portfolio that needs separate ad-to-page paths, not one destination."],
   ["Market context", "Founded 1948, manufacturing at Jigani Industrial Area (Anekal Taluk, Bengaluru); estimates put the business at roughly 200 people - a serious mid-size regional player."],
 ],
 "scores": {
   "Creative Variety": [6, "#F59E0B"],
   "UGC & Social Proof": [4, "#EF4444"],
   "Copy & Hook Strength": [6, "#F59E0B"],
   "Landing Page CRO": [4, "#EF4444"],
   "Tracking & CAPI": [5, "#F59E0B"],
   "Retargeting Depth": [4, "#EF4444"],
 },
 "findings": [
   "<b>One destination for three different buyers:</b> a cafe owner looking for a vending machine, a household buying filter coffee, and a CoCo outlet visitor are three different funnels. With 77 creatives live, the ad copy is already segmented - the landing pages are not.",
   "<b>Vending is your B2B goldmine:</b> 'coffee vending machine' is a high-intent, high-LTV query with a long decision cycle. It needs a dedicated page with ROI proof (cups/day, payback), a lead form, and retargeting - not a generic products page.",
   "<b>Local store ads without local proof:</b> the HMT Road Mathikere local ad is the right move; it should land on a store page with timings, directions and one-tap call - and be measured per store.",
   "<b>No UGC around the ritual:</b> filter coffee is the most social drink in South India. The account shows little user-generated 'my morning filter coffee' content; this is free creative volume you are not collecting.",
 ],
 "competitors": [
   ["Blue Tokai / Third Wave (specialty)", "Strong D2C brand storytelling and subscription mechanics.", "Cothas wins on heritage + vending scale - say it in the ad and on the page."],
   ["Narasu's / regional filter coffee brands", "Deep retail distribution and price-led messaging.", "Own 'since 1948' authenticity and brew-quality proof in paid social."],
   ["B2B vending operators", "Direct sales teams with ROI calculators.", "Publish a vending ROI calculator page and retarget every download."],
 ],
 "wins": [
   ["WIN 1 - Landing pages: one page per buyer", "Split the paid traffic into three destinations: Household (filter coffee subscription), B2B (vending machine enquiry with ROI calculator + form), and Store (CoCo outlet locator with timings and directions).", "#EF4444", "#FEF2F2"],
   ["WIN 2 - Vending lead engine", "Turn the vending line into a lead machine: a dedicated page, a 10-field enquiry form, WhatsApp handoff, and a 3-touch retargeting sequence (case study -> ROI -> offer). B2B vending deals are worth many D2C orders each.", "#F59E0B", "#FFFBEB"],
   ["WIN 3 - UGC ritual campaign", "Run a monthly #MyCothasFilter contest collecting customer photos/videos; the best 10 become paid creatives. Zero production cost, real social proof, endless creative supply.", "#10B981", "#ECFDF5"],
 ],
 "impact": [
   ["Metric", "Current (live)", "After Wins (est.)", "Impact"],
   ["Vending enquiries", "Traffic goes to general pages", "Dedicated ROI page + form", "Higher lead capture, better lead quality"],
   ["Local ad conversion", "Local ad -> generic site", "Local ad -> store page", "More calls and walk-ins per store"],
   ["Creative supply", "Agency-produced only", "+10 UGC creatives / month", "Lower cost per creative, higher trust"],
   ["Retargeting", "Shallow, brand-level", "Segment-level (household vs B2B)", "More repeat orders, more B2B pipeline"],
 ],
 "sources": [
   "Google Ads Transparency (region IN): 77 live creatives; advertiser Freeflow Creative Services India Pvt Ltd; Local ad 'Cothas Coffee HMT Road Mathikere' captured.",
   "cothas.com + /pages/contact-us: customercare@cothas.com; brand token #cb0024; GTM-K6SZV8J; vending and CoCo outlet lines.",
   "Company profile data (third-party): founded 1948; Jigani Industrial Area, Anekal Taluk, Bengaluru address; ~200 employees (estimate).",
 ],
 "outreach": [
  ["Email 1 (Day 1): 77 live Google ads, one destination - the Cothas audit",
   "Hi team,<br/><br/>I audit paid media for Bengaluru food brands. I inspected your live footprint this week: <b>77 Google creatives</b> running under Freeflow Creative Services, including Local store ads like your HMT Road Mathikere store. Genuinely good work - most heritage brands your age run zero paid.<br/><br/>The gap: a cafe owner searching 'coffee vending machine', a household buying filter coffee, and someone near a CoCo outlet all land on the same destination. Three buyers, one page.<br/><br/>Attachment: the 7-page Paid Media and Measurement Audit. Worth a short call?<br/><br/>- Smart Pursuit, Bengaluru | 7095024220"],
  ["Email 2 (Day 3): Your vending line is a B2B lead engine waiting to happen",
   "Hi team,<br/><br/>Second thought from the audit. 'Coffee vending machine' search intent is high-value and almost nobody in Indian coffee serves it with a proper page: ROI proof (cups/day, payback period), a short enquiry form, and WhatsApp handoff.<br/><br/>One vending contract can be worth hundreds of D2C orders. With 77 creatives already live, you have the traffic - it just needs a destination built for that buyer.<br/><br/>I can share the page structure we use for F&B B2B funnels if useful.<br/><br/>- Smart Pursuit | 7095024220"],
  ["Email 3 (Day 7): Free creatives: your customers' morning filter coffee",
   "Hi team,<br/><br/>Last idea from the audit. Filter coffee is the most photographed ritual in South India, and your account barely uses customer content. A monthly #MyCothasFilter collection - 10 best photos/videos become paid creatives - gives you fresh creative every month at zero production cost, with real social proof.<br/><br/>For a brand 'since 1948', customer ritual content is the strongest credibility asset you have.<br/><br/>Happy to map the full 30-day plan.<br/><br/>- Smart Pursuit | 7095024220"],
  ["Email 4 (Day 14): Closing the file on Cothas",
   "Hi team,<br/><br/>Wrapping up: the audit attached on Day 1 stands on three fixes - (1) split traffic into household / B2B vending / store destinations, (2) build the vending lead engine, (3) start a UGC ritual campaign.<br/><br/>No pressure if now is not the time. If you want, we can start with just the vending page and the enquiry flow this month.<br/><br/>- Smart Pursuit | 7095024220"],
 ],
 "verified_on": VERIFIED,
},
# ---------------------------------------------------------------- ANAND SWEETS
{
 "brand": "Anand Sweets",
 "website": "anandsweets.in",
 "instagram": "@anandsweetsindia",
 "contact": {"email": "care@anandsweets.net", "phone": "+91 80 2558 8992", "entity": "ANAND SWEETS AND SAVOURIES LLP", "address": "2nd Floor, 34/2 Anjanadri Heights, Dickenson Road, Bengaluru 560042"},
 "niche": "Sweets, Snacks & Corporate Gifting",
 "score": 8,
 "ads_active": 58,
 "headline": "58 Google ads, a Verified advertiser badge - and a 3-day delivery promise on a page where Swiggy is faster.",
 "stats": [("58", "Google creatives live"), ("Verified", "Google advertiser"), ("15+", "Bengaluru stores"), ("1988", "Founded")],
 "ad_intro": "Anand Sweets is one of the strongest paid footprints we found in Bengaluru food: 58 live Google Ads creatives under ANAND SWEETS AND SAVOURIES LLP - and Google shows the advertiser as <b>Verified</b>, which matters for a category where trust decides the order. The site carries 15+ Bengaluru stores, corporate gifting, wedding gifting and a Chak Now brand. The leak is the delivery promise: the site's own banner says Bangalore deliveries may take up to 3 days and points same-day buyers to Swiggy, Zomato or Ownly - so your paid traffic is being trained to leave and buy on someone else's app.",
 "ad_intelligence": [
   ["Google Ads (verified)", "58 live creatives; advertiser ANAND SWEETS AND SAVOURIES LLP shown as Google Verified - a real trust asset in the sweets category."],
   ["Delivery promise on site", "Site banner: 'Deliveries in Bangalore may take up to 3 Days' and routes same-day orders to Swiggy, Zomato or Ownly."],
   ["Sales channels", "Own D2C (Shopify), the 15+ stores (Budigere, Electronic City, Commercial Street, Whitefield, Sarjapur, Frazer Town, Jayanagar, Koramangala, Kammanahalli, Hennur and more), quick-commerce, plus Chak Now (chaknow.com)."],
   ["Gifting engine", "Corporate, personal and wedding gifting pages exist; corporate page carries care@anandsweets.net and Mon-Sat 10:00-17:30 timing; scale claim up to 2,000 boxes per order."],
   ["Category context", "Founded 1988; one of South India's largest mithai brands with international shipping; third-party estimates around USD 30M revenue and 500-1,000 employees."],
 ],
 "scores": {
   "Creative Variety": [6, "#F59E0B"],
   "UGC & Social Proof": [5, "#F59E0B"],
   "Copy & Hook Strength": [7, "#F59E0B"],
   "Landing Page CRO": [5, "#F59E0B"],
   "Tracking & CAPI": [5, "#F59E0B"],
   "Retargeting Depth": [4, "#EF4444"],
 },
 "findings": [
   "<b>You are advertising to send buyers to Swiggy:</b> the top-of-site banner tells every paid visitor that Bangalore delivery takes up to 3 days and that same-day means Swiggy / Zomato / Ownly. In sweets, a large share of urgent same-day demand is gift-driven (Diwali, house-warming, corporate) - the highest-margin occasions. Every one of those is being handed to an aggregator that owns the customer data and takes the margin.",
   "<b>Gifting is under-served by paid:</b> corporate and wedding gifting are the highest-order-value lines, yet the corporate page is reached by browsing. There should be a dedicated gifting campaign (search + Meta + LinkedIn for corporate HR/admin buyers) landing on the corporate page with the form and care@anandsweets.net immediately visible.",
   "<b>Festival/occasion calendar:</b> with a Verified Google badge and 58 creatives, the account can own the Bengaluru festival mithai demand window - but the creatives need an occasion calendar (Diwali, Ugadi, Sankranti, weddings) with pre-built audiences and geo radii per store.",
   "<b>Retargeting depth is the weakest score:</b> no visible retargeting structure for cart-abandoners or gifting-page visitors - both are high-value segments in this category.",
 ],
 "competitors": [
   ["Aggregators (Swiggy / Zomato / Ownly)", "Own same-day delivery expectation and take the customer data.", "Publish a store pick-up + express option; convert urgency on your own domain."],
   ["Bengaluru sweet chains (Kanti, Ganesh, Pai)", "Dense retail footprint, walk-in gifting flow.", "Win online gifting with corporate pages, GST invoice, and pan-India shipping proof."],
   ["National gifting brands", "Company-branded hampers and bulk invoicing.", "Lead with 'custom boxes up to 2,000 units' + India-wide shipping on the ad itself."],
 ],
 "wins": [
   ["WIN 1 - Stop sending paid traffic to Swiggy", "Add a store-pickup / express option on the product page and reframe the banner: same-day = pick up today, or order online for delivery. Only route out to aggregators when the SKU genuinely cannot ship.", "#EF4444", "#FEF2F2"],
   ["WIN 2 - Corporate gifting campaign", "Run a dedicated campaign to HR / admin / founders: Google search for 'corporate diwali gifts bangalore', Meta lookalikes, and a retargeting sequence - all landing on the corporate page with GST invoice, custom branding and the care@anandsweets.net enquiry flow above the fold.", "#F59E0B", "#FFFBEB"],
   ["WIN 3 - Occasion calendar + store-radius audiences", "Build a 12-month festival/weekly occasion calendar with pre-loaded creatives, geo-radius audiences around all 15+ Bengaluru stores, and cart-abandonment retargeting. One store radius = one local ad set.", "#10B981", "#ECFDF5"],
 ],
 "impact": [
   ["Metric", "Current (live)", "After Wins (est.)", "Impact"],
   ["Same-day demand", "Routed to Swiggy/Zomato/Ownly", "Pickup + express on own site", "Margin stays with Anand"],
   ["Corporate orders", "Organic browsing only", "Dedicated campaign + form + retargeting", "Higher AOV, calendar-driven pipeline"],
   ["Festival demand", "Broad creative base", "Occasion calendar + per-store geo ads", "Own the Bengaluru festival window"],
   ["Cart abandonment", "Not visibly retargeted", "3-touch retargeting flow", "Recovered revenue at low cost"],
 ],
 "sources": [
   "Google Ads Transparency (region IN): 58 live creatives; advertiser ANAND SWEETS AND SAVOURIES LLP marked Verified.",
   "anandsweets.in: delivery banner (up to 3 days), 15+ store contacts (Budigere, Electronic City, Commercial Street, Whitefield, Sarjapur, Frazer Town, Jayanagar, Koramangala, Kammanahalli, Hennur, Kanakapura, Devanahalli + airport counters), corporate gifting page with care@anandsweets.net.",
   "LinkedIn company page: 501-1,000 employees, Bangalore HQ, founded 1988; blog confirms bulk gifting scale (20 to 2,000 boxes).",
   "Third-party company data (estimates, labelled): ~USD 30M revenue.",
 ],
 "outreach": [
  ["Email 1 (Day 1): Your ads are sending buyers to Swiggy - the Anand Sweets audit",
   "Hi team,<br/><br/>I run paid-media audits for Bengaluru food brands. I checked your live footprint: <b>58 Google creatives</b> under Anand Sweets & Savouries LLP, and Google shows you as a <b>Verified</b> advertiser - a real asset in mithai, where trust decides the order.<br/><br/>The problem: your own top banner tells every paid visitor that Bangalore delivery takes up to 3 days and sends same-day buyers to Swiggy, Zomato or Ownly. That is the exact moment - festive, urgent, gift-driven - where mithai margins live, and it is being handed to an aggregator.<br/><br/>Attached is the 7-page Paid Media and Measurement Audit. Open to a 15-minute call?<br/><br/>- Smart Pursuit, Bengaluru | 7095024220"],
  ["Email 2 (Day 3): Corporate gifting is your highest-value leak",
   "Hi team,<br/><br/>Second finding from the audit: corporate and wedding gifting are your highest order values, and they are reached by browsing - not by paid campaigns.<br/><br/>A dedicated gifting campaign (search for 'corporate Diwali gifts Bangalore', Meta lookalikes, LinkedIn for HR/admin) landing on the corporate page with GST invoice, custom branding and care@anandsweets.net in the first screen would turn this into a pipeline instead of a page.<br/><br/>One 500-box order pays for the campaign many times over. I can share the full structure.<br/><br/>- Smart Pursuit | 7095024220"],
  ["Email 3 (Day 7): Own the festival calendar in Bengaluru",
   "Hi team,<br/><br/>With 15+ stores and 58 live creatives, you are a paid-media leader in this category - but festival demand is still fought on broad audiences.<br/><br/>The playbook: a 12-month occasion calendar (Diwali, Ugadi, Sankranti, wedding season) with pre-built creatives, geo-radius audiences around each store, and cart-abandonment retargeting. One store radius = one local ad set, measured per store.<br/><br/>Happy to walk through the calendar we would build for you.<br/><br/>- Smart Pursuit | 7095024220"],
  ["Email 4 (Day 14): Closing the file on Anand Sweets",
   "Hi team,<br/><br/>Final note: the audit stands on three fixes - (1) keep same-day demand on your own domain with pickup/express instead of routing to Swiggy, (2) run corporate gifting as a campaign, (3) build the festival calendar with per-store geo audiences and cart retargeting.<br/><br/>The document is yours regardless. If you would like us to implement the gifting campaign first, we can start next week.<br/><br/>- Smart Pursuit | 7095024220"],
 ],
 "verified_on": VERIFIED,
},
# ---------------------------------------------------------------- CHAI POINT
{
 "brand": "Chai Point",
 "website": "chaipoint.com",
 "instagram": "@chaipoint",
 "contact": {"email": "customercare@chaipoint.com", "phone": "+91 88801 41000", "entity": "Mountain Trail Foods Pvt Ltd", "address": "H1903, 4th Floor, Hustle Hub, 19th Main Rd, Agara Village, HSR Layout, Bengaluru 560102"},
 "niche": "Chai Retail & Workplace Beverages",
 "score": 7,
 "ads_active": 56,
 "headline": "150+ stores, 900,000 cups a day, 56 Google ads - and no B2B funnel for 8,100 workplaces.",
 "stats": [("56", "Google creatives live"), ("150+", "Stores, 19 cities"), ("900K+", "Cups per day"), ("8,100+", "Workplaces served")],
 "ad_intro": "Chai Point (Mountain Trail Foods Pvt Ltd) is running 56 live Google creatives - a healthy footprint for an omnichannel chai brand with 150+ stores across 19 cities and 900,000+ cups a day. The company also operates FICO, an investor-funded single-store model with strong published economics, and serves 8,100+ workplaces through its Brewing Bots. Two clear leaks: the B2B workplace side has no dedicated paid funnel, and the retail side lacks a store-radius local campaign to compete with app-first rivals.",
 "ad_intelligence": [
   ["Google Ads (verified)", "56 live creatives; advertiser Mountain Trail Foods Pvt Ltd."],
   ["Brand system on site", "Brand blue #18289c with orange accent #ff6c22; GA4 property G-EN77D2S0YH installed; modern site with 150+ store locator, FAQs, bulk-order and events pages."],
   ["What the brand says", "150+ stores in 19 cities; 900K+ cups a day; 8,100+ workplaces; 150+ Brewing Bots; 1,200-person team. Brewing Bots brew real tea leaves per cup vs premix vending - a strong B2B differentiator."],
   ["FICO (franchise-investor model)", "Public pages describe an investor model at INR 22-25L with 14-15% returns - meaning store-level economics are already published and socialised; store growth is a marketing-dependent engine."],
   ["Category context", "FY25 revenue INR 208.05 Cr with a INR 40.86 Cr loss and INR 14.5 Cr cash; an angel round reported around Apr 2026. Efficiency per store and per rupee of ad spend is the live board conversation."],
 ],
 "scores": {
   "Creative Variety": [6, "#F59E0B"],
   "UGC & Social Proof": [5, "#F59E0B"],
   "Copy & Hook Strength": [6, "#F59E0B"],
   "Landing Page CRO": [5, "#F59E0B"],
   "Tracking & CAPI": [6, "#F59E0B"],
   "Retargeting Depth": [4, "#EF4444"],
 },
 "findings": [
   "<b>The B2B goldmine has no funnel:</b> 8,100+ workplaces, 150+ Brewing Bots, and a genuine product difference (real tea leaves vs premix) - yet there is no paid campaign targeting office admin / HR / facility managers with a 'book a demo' path. This is the highest-LTV line in the business and it is running on organic reach.",
   "<b>No store-radius campaigns:</b> 150+ stores and no visible local ad structure per store. With app-first competitors buying hyperlocal inventory, each store should have its own radius campaign measured on walk-ins.",
   "<b>Store economics need marketing support:</b> with published FICO returns of 14-15% depending on store performance and FY25 showing a loss, store-level demand generation (local ads + review velocity + first-order offers) directly protects the franchise story.",
   "<b>Retail retargeting missing:</b> chai is a daily habit - the highest-frequency category in F&B. A missed retargeting structure (first order, then subscription/bulk) leaves the cheapest repeat revenue on the table.",
 ],
 "competitors": [
   ["Blue Tokai / Third Wave (premium cafes)", "Strong owned-brand cafe experience and loyalty.", "Chai Point's scale + Brewing Bot tech is unique - lead with it."],
   ["Local chai chains & tapris", "Price and proximity; impulse purchase.", "Own the '100% real tea leaves, no premix' quality story in ads."],
   ["Coffee vending incumbents (Nescafe, Chaayos workplace)", "Deep B2B sales teams.", "Run paid to create inbound demo requests; sales closes faster."],
 ],
 "wins": [
   ["WIN 1 - B2B workplace funnel", "Build a 'Book a Brewing Bot demo' landing page: cups/day calculator, workplace photos, install timeline, client logos - then run Google search for 'office tea vending machine', LinkedIn for admin/HR titles, and retarget every visitor with two case-study ads.", "#EF4444", "#FEF2F2"],
   ["WIN 2 - Store-radius local campaigns", "Give the top 25 Bengaluru stores each a geo-radius campaign (3-5 km) with store-specific creatives, first-order offer, and per-store measurement - then scale the winners.", "#F59E0B", "#FFFBEB"],
   ["WIN 3 - Habit retargeting", "Chai is daily. Retarget every customer with a 3-step flow: first order -> bundle/subscription -> gifting. Add WhatsApp opt-in at checkout for the highest-frequency channel in F&B.", "#10B981", "#ECFDF5"],
 ],
 "impact": [
   ["Metric", "Current (live)", "After Wins (est.)", "Impact"],
   ["Workplace leads", "Organic only", "Paid B2B funnel + retargeting", "Inbound pipeline per city"],
   ["Store walk-ins", "No local ad structure", "Radius campaigns on top 25 stores", "Measurable lift per store"],
   ["Repeat orders", "No visible retargeting flow", "3-step habit flow + WhatsApp", "Higher frequency, lower CAC"],
   ["Franchise story", "Economics published", "Proven local demand generation", "Easier FICO investor acquisition"],
 ],
 "sources": [
   "Google Ads Transparency (region IN): 56 live creatives; advertiser Mountain Trail Foods Pvt Ltd.",
   "chaipoint.com: 150+ stores / 19 cities, 900K+ cups/day, 8,100+ workplaces, 150+ Brewing Bots; brand tokens #18289c / #ff6c22; GA4 G-EN77D2S0YH.",
   "fico.chaipoint.com: published investor model (INR 22-25L, 14-15% returns).",
   "Public FY25 coverage (Mountain Trail Foods): revenue INR 208.05 Cr, loss INR 40.86 Cr, cash INR 14.5 Cr; angel round reported Apr 2026.",
   "Contact path: customercare@chaipoint.com / feedback@chaipoint.com / +91 88801 41000; HQ in HSR Layout, Bengaluru 560102.",
 ],
 "outreach": [
  ["Email 1 (Day 1): 8,100 workplaces, 150+ Brewing Bots, no paid B2B funnel",
   "Hi team,<br/><br/>I audit paid media for Bengaluru food brands. I checked your live footprint: <b>56 Google creatives</b> under Mountain Trail Foods, a genuinely modern site (GA4 G-EN77D2S0YH), and the numbers you publish are strong - 150+ stores, 900,000 cups a day, 8,100 workplace clients.<br/><br/>Here is the leak: the B2B side - your highest-value line - has no paid funnel. No 'book a demo' path for office admins searching for tea vending, while your Brewing Bot (real tea leaves, not premix) is a genuinely superior product to every coffee-only incumbent.<br/><br/>Attached: the 7-page Paid Media and Measurement Audit. Worth 15 minutes?<br/><br/>- Smart Pursuit, Bengaluru | 7095024220"],
  ["Email 2 (Day 3): The Brewing Bot deserves a demo funnel",
   "Hi team,<br/><br/>Following the audit: 8,100 workplaces is proof the product sells - but it is selling through people, not paid demand.<br/><br/>A simple funnel - landing page with cups/day calculator and install timeline, Google search on 'office tea vending machine', LinkedIn targeting admin/HR titles, and a two-ad retargeting sequence with case studies - turns that into inbound pipeline per city.<br/><br/>Happy to share the page structure and the exact targeting we would use.<br/><br/>- Smart Pursuit | 7095024220"],
  ["Email 3 (Day 7): 150 stores, zero store-radius campaigns",
   "Hi team,<br/><br/>Third finding from the audit. With 150+ stores in 19 cities, you are competing with app-first brands that buy hyperlocal inventory around their outlets. Your top Bengaluru stores should each have a 3-5 km radius campaign with a store-specific first-order offer - measured on walk-ins, not just clicks.<br/><br/>25 stores is enough to build the template, prove the lift, and then scale city by city. It also gives your FICO investors a demand-generation story, not just a product story.<br/><br/>- Smart Pursuit | 7095024220"],
  ["Email 4 (Day 14): Closing the file on Chai Point",
   "Hi team,<br/><br/>Last note from me: the audit's three fixes are (1) build the workplace/Brewing Bot demo funnel, (2) give the top 25 stores radius campaigns with store-level measurement, (3) start habit retargeting with a WhatsApp opt-in - chai is a daily drink, and that is your cheapest repeat revenue.<br/><br/>The audit is yours to keep. If you want, we can start with the B2B demo funnel this month.<br/><br/>- Smart Pursuit | 7095024220"],
 ],
 "verified_on": VERIFIED,
},
]
