# -*- coding: utf-8 -*-
"""Food / Bangalore audit leads - Part B (all data verified live on 02 Oct 2026)."""

VERIFIED = "02 OCT 2026"

LEADS_B = [
# ---------------------------------------------------------------- BAKERS DOZEN
{
 "brand": "The Baker's Dozen",
 "website": "thebakersdozen.in",
 "instagram": "@thebakersdozen",
 "contact": {"email": "fresh@thebakersdozen.in", "phone": "+91 9082857741", "entity": "Mimansa Industries Pvt Ltd", "address": "Ellisbridge, Ahmedabad 380006 (grievance officer: Neel Shah)"},
 "niche": "Sourdough Bakery & Retail",
 "score": 7,
 "ads_active": 35,
 "headline": "35 Google ads, 1M+ sourdoughs - but the ad clicks have no bakery destination built for them.",
 "stats": [("35", "Google creatives live"), ("300+", "Cities served"), ("2000+", "Retail touchpoints"), ("1M+", "Sourdoughs baked")],
 "ad_intro": "The Baker's Dozen is a rare case in Indian bakery: a brand that scaled sourdough from a Bengaluru kitchen to 300+ cities and 2,000+ retail touchpoints, bakes 1M+ sourdoughs, and still runs paid media properly - 35 live Google creatives under Mimansa Industries Pvt Ltd. The opportunity is that the paid traffic is buying a brand that sells in 300+ cities and on quick-commerce apps, so the destination must answer 'where is my nearest loaf?' in one tap. It currently does not.",
 "ad_intelligence": [
   ["Google Ads (verified)", "35 live creatives; advertiser Mimansa Industries Pvt Ltd."],
   ["Distribution reality", "300+ cities, 2,000+ touchpoints and quick-commerce channels (Blinkit / Zepto / Instamart class), plus own D2C storefront - meaning a large share of demand is 'buy now, nearest place'."],
   ["Brand assets", "13+ years of sourdough credibility, 1M+ sourdoughs baked - exceptional trust proof that no competitor can copy quickly."],
   ["Contact path on site", "fresh@thebakersdozen.in / +91 9082857741; grievance officer Neel Shah (registered entity Mimansa Industries Pvt Ltd, Ellisbridge, Ahmedabad 380006)."],
   ["Category context", "Indian bakery + sourdough is in a premiumisation wave driven by quick-commerce. Shelf 2.0 brands win by owning search for 'sourdough near me' and 'fresh bread delivery' in their cities."],
 ],
 "scores": {
   "Creative Variety": [6, "#F59E0B"],
   "UGC & Social Proof": [5, "#F59E0B"],
   "Copy & Hook Strength": [6, "#F59E0B"],
   "Landing Page CRO": [4, "#EF4444"],
   "Tracking & CAPI": [5, "#F59E0B"],
   "Retargeting Depth": [4, "#EF4444"],
 },
 "findings": [
   "<b>No 'nearest loaf' destination:</b> the paid click does not land on a store/availability page for the searcher's city. For a brand in 300+ cities, that is the single biggest conversion leak - the buyer's question is 'where do I get it today', and the answer takes too many taps.",
   "<b>Quick-commerce traffic is not captured:</b> shoppers search 'sourdough Blinkit / bread delivery near me'. Unless you own those search results and route them to the right channel with tracking, the aggregator keeps the customer relationship - and the repeat purchase.",
   "<b>1M+ sourdoughs is an unused ad asset:</b> that is a decade of trust compressed into one line. It should be in the ad hook, the landing page hero, and the retargeting creative - it is the strongest proof point in the entire Indian sourdough market.",
   "<b>Retargeting and email capture:</b> no visible retargeting for product viewers or store-locator users; bakery is a weekly-repeat category where a 3-touch flow is cheap and effective.",
 ],
 "competitors": [
   ["Le 15 Patisserie / premium bakery chains", "Cafe experience + strong Instagram brand.", "BD has national distribution - own 'delivered fresh' against cafe-only brands."],
   ["Quick-commerce private labels", "Cheapest price, fastest delivery, top of app search.", "Own the brand search and the 'sourdough near me' query so buyers ask for you by name."],
   ["Local artisanal bakeries per city", "Hyperlocal freshness and price.", "Win with 'baked in Bengaluru, shipped 300+ cities' proof and consistency."],
 ],
 "wins": [
   ["WIN 1 - Availability-first landing", "Build a 'Find your loaf' page: enter pin code -> shows nearest store + quick-commerce options + home delivery ETA. Route all paid traffic there with city/pin pre-set from the ad. This is the single highest-leverage change.", "#EF4444", "#FEF2F2"],
   ["WIN 2 - Prove 1M+ sourdoughs everywhere", "Turn the 1M+ milestone into the ad hook, landing hero, and retargeting creative (counter, customer reviews, bake-day photos). Add a 20-second 'inside the bake' Reel as the top-of-funnel creative.", "#F59E0B", "#FFFBEB"],
   ["WIN 3 - Weekly repeat engine", "Bakery is a weekly habit: retarget every product viewer and store-locator user with a 3-touch flow (taste proof -> bundle offer -> subscription), and capture email/WhatsApp at the availability page.", "#10B981", "#ECFDF5"],
 ],
 "impact": [
   ["Metric", "Current (live)", "After Wins (est.)", "Impact"],
   ["Ad-to-availability steps", "Multiple taps to check stock", "Pin-code availability page", "Higher conversion on same traffic"],
   ["Brand search capture", "Partial", "Own 'sourdough near me' per city", "Cheaper, higher-intent traffic"],
   ["Repeat purchase", "No visible flow", "3-touch repeat + subscription", "Higher LTV per customer"],
   ["Proof usage", "1M+ sourdoughs under-used", "In hook, hero and retargeting", "Higher CTR and trust at equal spend"],
 ],
 "sources": [
   "Google Ads Transparency (region IN): 35 live creatives; advertiser Mimansa Industries Pvt Ltd.",
   "thebakersdozen.in + /contact-us: fresh@thebakersdozen.in, +91 9082857741, grievance officer Neel Shah; brand stats 13+ years, 300+ cities, 2,000+ touchpoints, 1M+ sourdoughs; quick-commerce channels live.",
 ],
 "outreach": [
  ["Email 1 (Day 1): 35 live ads, 300+ cities - but the click has nowhere to land",
   "Hi team,<br/><br/>I run paid-media audits for food brands from Bengaluru. I inspected your live footprint: <b>35 Google creatives</b> under Mimansa Industries Pvt Ltd - and 1M+ sourdoughs baked, which is the strongest trust proof in Indian sourdough.<br/><br/>The leak: your paid clicks do not land on a 'where is my nearest loaf' page. For a brand in 300+ cities with quick-commerce distribution, that question is the whole conversion. The buyer asks it, does not get one-tap answer, and the aggregator keeps the relationship.<br/><br/>Attached is a 2-page audit with 3 fixes. Open to a short call?<br/><br/>- Smart Pursuit, Bengaluru | 7095024220"],
  ["Email 2 (Day 3): The 'Find your loaf' page",
   "Hi team,<br/><br/>The one-page fix from the audit: a pin-code availability page that shows - in this order - nearest store, quick-commerce options, and home-delivery ETA. Pre-set the pin from the ad so the buyer lands on an answer, not a homepage.<br/><br/>Everything else (creative, retargeting) amplifies this page. It is also the best email/WhatsApp capture point you have, in a weekly-repeat category.<br/><br/>I can share the wireframe we would use.<br/><br/>- Smart Pursuit | 7095024220"],
  ["Email 3 (Day 7): 1M sourdoughs is a paid-media asset",
   "Hi team,<br/><br/>Quick idea from the audit. '1M+ sourdoughs baked' is stronger than any discount you can offer - it is proof. Put it in the ad hook, the landing hero, and the retargeting creative, and add a 20-second 'inside the bake' Reel at the top of the funnel.<br/><br/>Bakery buyers are buying consistency and craft. You have both, and you have receipts.<br/><br/>Happy to mock up three creatives around the milestone.<br/><br/>- Smart Pursuit | 7095024220"],
  ["Email 4 (Day 14): Closing the file on The Baker's Dozen",
   "Hi team,<br/><br/>Final note: the audit stands on three fixes - (1) pin-code availability landing page for all paid traffic, (2) put the 1M+ sourdough proof into hook/hero/retargeting, (3) build the weekly repeat flow with email/WhatsApp capture.<br/><br/>The audit is yours to keep. If you want us to start, the availability page is a one-week build.<br/><br/>- Smart Pursuit | 7095024220"],
 ],
 "verified_on": VERIFIED,
},
# ---------------------------------------------------------------- EARLY FOODS
{
 "brand": "Early Foods",
 "website": "earlyfoods.com",
 "instagram": "@earlyfoods",
 "contact": {"email": "hello@earlyfoods.com", "phone": "+91 8049670521", "entity": "Early Foods Pvt Ltd", "address": "Bengaluru, Karnataka"},
 "niche": "Organic Baby & Toddler Food",
 "score": 7,
 "ads_active": 30,
 "headline": "30 Google ads for a clean-label baby brand - but the parent's first question is unanswered in the ad.",
 "stats": [("30", "Google creatives live"), ("Organic", "Clean-label range"), ("Shopify", "D2C + global store"), ("Bengaluru", "Home market")],
 "ad_intro": "Early Foods is a Bengaluru clean-label baby and toddler food brand running 30 live Google creatives under Early Foods Pvt Ltd - a solid paid base in a category where trust is the entire purchase decision. The brand also runs a global storefront (global.earlyfoods.com). The leak is message-to-proof mapping: parents buy after they see ingredients, age-appropriateness and safety, yet the ad and landing path lead with the product rather than the reassurance stack that removes fear.",
 "ad_intelligence": [
   ["Google Ads (verified)", "30 live creatives; advertiser Early Foods Pvt Ltd."],
   ["D2C setup", "Shopify storefront with a global store (global.earlyfoods.com) - i.e. international shipping is already live, which is an unusual growth channel for an Indian baby-food brand."],
   ["Contact path on site", "hello@earlyfoods.com / +91 8049670521."],
   ["Category dynamics", "Indian baby-food is dominated by legacy multinationals on shelf; D2C challengers win on clean-label proof (no preservatives, no added sugar, millet-based, made fresh) plus trust signals - certifications, ingredient transparency, and parent reviews."],
   ["Buyer psychology", "First-time parents research heavily before the first order and repurchase on subscription for 18-36 months. First-order CAC is amortised over a long, predictable LTV - so conversion rate at the first touch matters more than in almost any other food category."],
 ],
 "scores": {
   "Creative Variety": [5, "#F59E0B"],
   "UGC & Social Proof": [4, "#EF4444"],
   "Copy & Hook Strength": [5, "#F59E0B"],
   "Landing Page CRO": [5, "#F59E0B"],
   "Tracking & CAPI": [5, "#F59E0B"],
   "Retargeting Depth": [4, "#EF4444"],
 },
 "findings": [
   "<b>Fear is the real competitor:</b> parents do not compare you to another brand - they compare the risk of trying you to the safety of a known multinational. The ad and page should open with the reassurance stack: age-appropriate, ingredient list, how it is made, what is NOT in it, and parent proof.",
   "<b>No visible parent UGC engine:</b> the highest-converting asset in baby food is another parent's face and words. There is no visible system to collect, permission, and rotate parent videos into ads.",
   "<b>First-order friction:</b> in a research-heavy category, a trial pack / sampler bundle with a clear 'start here by age' path converts far better than a full-price single SKU.",
   "<b>Retention not monetised:</b> baby food is an 18-36 month subscription habit. A stage-based flow (6m/9m/12m/18m) with WhatsApp reminders and auto-replenish is the highest-margin system you could build - and it is not visible today.",
 ],
 "competitors": [
   ["Legacy multinationals (Cerelac class)", "Shelf ubiquity and grandmother-level brand trust.", "Attack on ingredients: clean label, no preservatives, no refined sugar - with proof on the page."],
   ["Other D2C baby-food brands", "Subscription bundles and parent communities.", "Win with stage-based bundles, parent UGC, and global shipping proof."],
   ["Homemade (the real alternative)", "Free, trusted, labour-intensive.", "Position as 'homemade, without the work' with ingredient transparency."],
 ],
 "wins": [
   ["WIN 1 - Trust-first landing path", "Rebuild the ad-to-page path around the reassurance stack: age selector, full ingredient list, 'what's not inside' panel, certifications, and parent reviews above the fold. Route each ad to the matching age page, not the homepage.", "#EF4444", "#FEF2F2"],
   ["WIN 2 - Parent UGC engine", "Offer a starter bundle to 50 existing customers in exchange for a 20-second video ('what I feed my 10-month-old'). Rotate the top 12 as paid creatives monthly - real faces, real kitchens, zero production cost.", "#F59E0B", "#FFFBEB"],
   ["WIN 3 - Stage-based subscription flow", "Build 6m / 9m / 12m / 18m bundles with auto-replenish, WhatsApp reminders and a 'grow with us' upgrade path. Baby food is a two-year subscription - price it like one.", "#10B981", "#ECFDF5"],
 ],
 "impact": [
   ["Metric", "Current (live)", "After Wins (est.)", "Impact"],
   ["First-order conversion", "Product-first pages", "Trust-first, age-matched pages", "Higher CVR on same traffic"],
   ["Creative proof", "Brand-produced", "+12 parent UGC creatives/quarter", "Higher CTR, lower CPC"],
   ["Repeat revenue", "Ad-hoc repurchase", "Stage-based subscription", "Predictable 18-36 month LTV"],
   ["Global channel", "Store live, unadvertised", "Test campaigns (UAE/SG/US)", "New channel at low incremental cost"],
 ],
 "sources": [
   "Google Ads Transparency (region IN): 30 live creatives; advertiser Early Foods Pvt Ltd.",
   "earlyfoods.com + global.earlyfoods.com: hello@earlyfoods.com, +91 8049670521; Shopify D2C and global storefront.",
   "Category benchmark research on Indian baby-food D2C (clean-label positioning, subscription retention).",
 ],
 "outreach": [
  ["Email 1 (Day 1): 30 live ads for Early Foods - the trust gap in the first 5 seconds",
   "Hi team,<br/><br/>I audit paid media for Bengaluru food brands. I checked your live footprint: <b>30 Google creatives</b> under Early Foods Pvt Ltd, plus a global storefront already live - strong setup for a clean-label brand.<br/><br/>One finding: in baby food, parents are not choosing between brands - they are weighing the risk of trying you against a known multinational. Your ads and landing path lead with product; they should lead with reassurance: age-appropriate, full ingredient list, what is NOT inside, and other parents' faces.<br/><br/>Attached: a 2-page audit with 3 fixes. Open to 15 minutes?<br/><br/>- Smart Pursuit, Bengaluru | 7095024220"],
  ["Email 2 (Day 3): Your best creative is sitting in your customers' kitchens",
   "Hi team,<br/><br/>Following the audit: the highest-converting asset in baby food is another parent's face and words - and there is no visible system collecting them.<br/><br/>Simple version: offer a starter bundle to 50 existing customers for a 20-second video ('what I feed my 10-month-old'). Rotate the top 12 as paid creatives every month. Real kitchens, real babies, zero production cost.<br/><br/>Happy to share the brief and permission/consent flow.<br/><br/>- Smart Pursuit | 7095024220"],
  ["Email 3 (Day 7): Baby food is a 2-year subscription - is it priced like one?",
   "Hi team,<br/><br/>Third finding. A parent who starts at 6 months stays 18-36 months. That predictable LTV changes everything: stage-based bundles (6m / 9m / 12m / 18m) with auto-replenish and WhatsApp reminders turn a one-off order into a two-year relationship.<br/><br/>Add a 'grow with us' upgrade path and you have a retention system no multinational shelf brand can match.<br/><br/>Want me to map the bundle ladder against your SKUs?<br/><br/>- Smart Pursuit | 7095024220"],
  ["Email 4 (Day 14): Closing the file on Early Foods",
   "Hi team,<br/><br/>Final note: the audit's three fixes are (1) trust-first, age-matched landing pages, (2) a parent UGC engine, (3) stage-based subscription bundles with WhatsApp reminders.<br/><br/>Also worth a test later: you already run a global store - the UAE, Singapore and US Indian-parent audiences are reachable at low incremental cost.<br/><br/>The audit is yours. If you want to start, the UGC engine is the fastest win.<br/><br/>- Smart Pursuit | 7095024220"],
 ],
 "verified_on": VERIFIED,
},
# ---------------------------------------------------------------- ID FRESH
{
 "brand": "iD Fresh Food",
 "website": "idfreshfood.com",
 "instagram": "@idfreshfood",
 "contact": {"email": "customercare@idfreshfood.com", "phone": "+91 9739910521", "entity": "iD Fresh Food (India) Pvt Ltd", "address": "Attibele, Anekal Taluk, Bengaluru 562107"},
 "niche": "Fresh Batter & Ready-to-Cook",
 "score": 8,
 "ads_active": 1,
 "headline": "INR 681 Cr revenue - and ONE live Google ad. That is not a budget problem, it is a capture problem.",
 "stats": [("1", "Google creative live"), ("INR 681 Cr", "FY25 revenue"), ("INR 25.9 Cr", "FY25 PAT"), ("Bengaluru", "Global HQ")],
 "ad_intro": "iD Fresh Food closed FY25 at INR 681.4 Cr revenue with INR 25.87 Cr PAT and took INR 1,300 Cr from Apax in Jan 2026, with an IPO targeted around Oct 2027. That is a company that must show predictable, efficient demand. Yet Google Ads Transparency shows exactly <b>one</b> live creative for idfreshfood.com, and it runs under Blink Digital India Pvt Ltd - i.e. the brand's Google presence is essentially a single agency-run ad. Every search for 'idli batter near me', 'malabar parota', 'preservative-free batter' is being answered by aggregators and competitors instead.",
 "ad_intelligence": [
   ["Google Ads (verified)", "1 live creative; advertiser of record Blink Digital India Pvt Ltd (agency-run)."],
   ["Business momentum", "FY25 revenue INR 681.4 Cr, PAT INR 25.87 Cr; INR 1,300 Cr investment from Apax (Jan 2026); IPO targeted ~Oct 2027."],
   ["Distribution", "Preservative-free batter and ready-to-cook range across retail + quick-commerce in India and export markets; Bengaluru HQ with the flagship plant at Attibele, Anekal Taluk (562107)."],
   ["Contact path on site", "customercare@idfreshfood.com / +91 9739910521."],
   ["Category context", "Fresh batter is a high-frequency, habit-driven category: the same household buys weekly. That makes paid search + retargeting unusually profitable - and makes the single-ad footprint a glaring gap."],
 ],
 "scores": {
   "Creative Variety": [2, "#EF4444"],
   "UGC & Social Proof": [4, "#EF4444"],
   "Copy & Hook Strength": [5, "#F59E0B"],
   "Landing Page CRO": [5, "#F59E0B"],
   "Tracking & CAPI": [5, "#F59E0B"],
   "Retargeting Depth": [3, "#EF4444"],
 },
 "findings": [
   "<b>Brand demand is being harvested by others:</b> with one live ad, searches for your own category - 'idli batter home delivery', 'malabar parota online', 'preservative free batter' - are won by quick-commerce and smaller D2C brands. Before an IPO, that gap is a valuation issue, not just a marketing issue.",
   "<b>Retail + quick-commerce + D2C are three different funnels:</b> in-store buyers need 'find near me' and offers; quick-commerce buyers need brand reinforcement; D2C buyers need subscription and freshness proof. One ad cannot serve all three.",
   "<b>Habit category, no habit engine:</b> batter is bought weekly. A subscribe-and-save flow with WhatsApp reminders is the most profitable mechanic available - and it does not depend on new customers.",
   "<b>IPO-readiness lens:</b> investors look at channel mix and demand durability. Owned D2C recurring revenue (subscriptions) is the most valuable line you can add before Oct 2027 - and paid media is the cheapest way to build it.",
 ],
 "competitors": [
   ["Quick-commerce private-label batter", "Price + 10-minute delivery + app search dominance.", "Own brand search and quality story; make 'preservative-free' the visible differentiator."],
   ["Regional fresh-batter brands", "Local price and freshness.", "National consistency + export-grade proof at scale."],
   ["Homemade batter", "Free, trusted.", "Win on time saved + zero preservatives, with transparent ingredient proof."],
 ],
 "wins": [
   ["WIN 1 - Build the search moat", "Launch full-funnel Google search across brand, category and competitor terms ('idli batter', 'dosa batter home delivery', 'malabar parota online', 'batter without preservatives') with geo-split landing pages: nearest store / quick-commerce / subscribe-and-save.", "#EF4444", "#FEF2F2"],
   ["WIN 2 - Subscription engine", "Weekly batter is a subscription category. Build subscribe-and-save with a 10-15% incentive, WhatsApp reminders, and a freshness guarantee - then retarget every D2C buyer into it.", "#F59E0B", "#FFFBEB"],
   ["WIN 3 - Freshness proof at scale", "Turn the preservative-free, cold-chain process into ad creative: a '48-hour batter' film, plant-to-kitchen traceability, and customer 'no preservatives' proof - the assets that justify a premium over private label.", "#10B981", "#ECFDF5"],
 ],
 "impact": [
   ["Metric", "Current (live)", "After Wins (est.)", "Impact"],
   ["Google presences", "1 live creative", "Full-funnel search + local + retargeting", "Category demand captured, not lost"],
   ["Recurring revenue", "Not visible", "Subscribe-and-save + WhatsApp", "Predictable D2C revenue before IPO"],
   ["Brand vs private label", "Price-competed", "Freshness/preservative-free proof", "Premium positioning defended"],
   ["Retail footfall", "No local ad structure", "Geo campaigns per city", "Store-level demand lift"],
 ],
 "sources": [
   "Google Ads Transparency (region IN): 1 live creative; advertiser Blink Digital India Pvt Ltd.",
   "idfreshfood.com/contact-us: customercare@idfreshfood.com, +91 9739910521, Attibele plant, Anekal Taluk, Bangalore 562107.",
   "Public FY25 coverage: revenue INR 681.4 Cr, PAT INR 25.87 Cr; INR 1,300 Cr Apax investment (Jan 2026); IPO targeted ~Oct 2027.",
 ],
 "outreach": [
  ["Email 1 (Day 1): INR 681 Cr revenue, one live Google ad - here is the audit",
   "Hi team,<br/><br/>I run paid-media audits for food brands from Bengaluru. I checked your live footprint this week: Google Ads Transparency shows <b>one</b> live creative for idfreshfood.com, running under Blink Digital India Pvt Ltd.<br/><br/>That is remarkable for a brand at INR 681 Cr revenue with an IPO in view - and it means every 'idli batter home delivery', 'malabar parota online' or 'preservative-free batter' search is being answered by quick-commerce and smaller D2C brands, not by you.<br/><br/>I have attached a 2-page audit with 3 fixes, including the subscription engine that would add recurring revenue before your IPO window. 15 minutes this week?<br/><br/>- Smart Pursuit, Bengaluru | 7095024220"],
  ["Email 2 (Day 3): The category searches you are not buying",
   "Hi team,<br/><br/>Following up: the audit recommends a search moat across brand, category and competitor terms, with three landing paths - nearest store, quick-commerce, and subscribe-and-save.<br/><br/>Batter is bought weekly by the same household, so search + retargeting here is unusually profitable: you are not buying new customers, you are capturing demand that already exists in your category.<br/><br/>I can send the keyword clusters and geo-split structure we would use.<br/><br/>- Smart Pursuit | 7095024220"],
  ["Email 3 (Day 7): Subscribe-and-save is your pre-IPO revenue line",
   "Hi team,<br/><br/>One more from the audit, and it is the one I would prioritise before an IPO: weekly batter is a subscription category, and subscribe-and-save with a 10-15% incentive and WhatsApp reminders converts existing buyers into predictable recurring revenue.<br/><br/>Owned D2C recurring revenue is the most valuable line you can add to the story - and paid media is the cheapest way to build it.<br/><br/>Happy to map the mechanics (offer, cadence, retention curve) for you.<br/><br/>- Smart Pursuit | 7095024220"],
  ["Email 4 (Day 14): Closing the file on iD Fresh",
   "Hi team,<br/><br/>Last note: the audit's three fixes are (1) build the search moat with three landing paths, (2) launch subscribe-and-save with WhatsApp reminders, (3) turn the preservative-free process into ad creative that defends your premium.<br/><br/>The audit is yours. If you want, we can start with the search structure and show results before any creative work.<br/><br/>- Smart Pursuit | 7095024220"],
 ],
 "verified_on": VERIFIED,
},
# ---------------------------------------------------------------- THIRD WAVE
{
 "brand": "Third Wave Coffee",
 "website": "thirdwavecoffeeroasters.com",
 "instagram": "@thirdwavecoffeeindia",
 "contact": {"email": "orders@thirdwavecoffee.in", "phone": "+91 80 47108111", "entity": "Third Wave Coffee", "address": "HSR Layout, Bengaluru 560102"},
 "niche": "Specialty Coffee Retail",
 "score": 7,
 "ads_active": 0,
 "headline": "Zero live Google ads for a brand with USD 112M raised - the search demand is all going somewhere else.",
 "stats": [("0", "Google creatives live"), ("USD 112M", "Raised to date"), ("HSR Layout", "Bengaluru HQ"), ("Series D", "Aug 2026 (reported)")],
 "ad_intro": "Third Wave Coffee is one of India's best-known specialty coffee brands, with USD 112M raised and a Series D reported in Aug 2026. Which is why this audit is unusual: Google Ads Transparency shows <b>zero</b> live creatives for its domain. This is verified on the Google side only - we did not confirm its Meta inventory in this pass, and we do not report what we did not verify. On the Google side, every 'coffee near me', 'cold brew', 'coffee beans online' and store-level search around its outlets is being answered by competitors.",
 "ad_intelligence": [
   ["Google Ads (verified)", "0 live creatives on Google Ads Transparency for thirdwavecoffeeroasters.com (region IN)."],
   ["Site setup", "thirdwavecoffee.in 301-redirects to www.thirdwavecoffeeroasters.com; Shopify storefront (theme id 133405212742) with GTM installed and 8+ apps loaded - a fairly heavy stack for a beverage storefront."],
   ["Brand scale", "USD 112M raised; Series D reported Aug 2026; brand-reported footprint around 100 outlets plus a coffee bean D2C line - i.e. both hyperlocal (store visits) and e-commerce (beans/subscriptions) demand exist."],
   ["Contact path on site", "orders@thirdwavecoffee.in / +91 80 47108111, HSR Layout, Bengaluru 560102."],
   ["Category context", "Specialty coffee is the most searched premium F&B category in Bengaluru. Competitors (Blue Tokai, Third Wave, Sleepy Owl, Rage, plus hundreds of cafes) compete on brand search, 'near me' queries and bean subscriptions - all of which are Google/Meta purchase moments."],
 ],
 "scores": {
   "Creative Variety": [4, "#EF4444"],
   "UGC & Social Proof": [6, "#F59E0B"],
   "Copy & Hook Strength": [6, "#F59E0B"],
   "Landing Page CRO": [5, "#F59E0B"],
   "Tracking & CAPI": [5, "#F59E0B"],
   "Retargeting Depth": [3, "#EF4444"],
 },
 "findings": [
   "<b>Zero Google presence means store demand leaks daily:</b> every 'coffee near me', 'best cafe Indiranagar', 'cold brew delivery' query in the cities where outlets exist is being answered without you. Local store campaigns are the cheapest walk-in acquisition channel available to a cafe chain.",
   "<b>Bean subscriptions are a Google/Meta purchase:</b> the D2C bean line competes with Blue Tokai et al, who buy category search. Coffee beans are a repeat subscription purchase - exactly the profile that paid search + retargeting serves best.",
   "<b>Heavy Shopify stack, no paid layer:</b> 8+ apps and a Shopify theme that is several versions old creates a slow, app-heavy storefront - and speed multiplies every paid campaign you run. Fix the storefront weight before scaling spend.",
   "<b>Not verified: Meta.</b> Our audit verifies what it can prove. Google is verified at zero; a Meta check is the first step of implementation. We will not claim data we have not seen.",
 ],
 "competitors": [
   ["Blue Tokai Coffee Roasters", "Aggressive category search + subscription-first D2C.", "Buy 'coffee beans online' and 'cold brew' terms; match their subscription mechanics."],
   ["Sleepy Owl / Rage Coffee", "D2C-first, heavy Meta + Google retargeting.", "Third Wave's cafe footprint is a trust advantage - convert store visitors into subscribers."],
   ["Local specialty cafes", "Hyperlocal presence and Google Business Profile visibility.", "Local store-ad campaigns plus review velocity per outlet."],
 ],
 "wins": [
   ["WIN 1 - Local store campaigns", "Launch per-store radius campaigns for the top 10 Bengaluru outlets with a first-visit offer, measured on store visits - the cheapest walk-in channel a cafe chain can buy.", "#EF4444", "#FEF2F2"],
   ["WIN 2 - Bean subscription engine", "Buy category search ('coffee beans online', 'cold brew', 'single origin coffee') and retarget every store visitor and bean buyer into a monthly subscription with free shipping.", "#F59E0B", "#FFFBEB"],
   ["WIN 3 - Storefront speed before spend", "Audit the 8+ Shopify apps and old theme, remove unused scripts, and pass Core Web Vitals before scaling paid - speed multiplies every rupee of paid traffic.", "#10B981", "#ECFDF5"],
 ],
 "impact": [
   ["Metric", "Current (live)", "After Wins (est.)", "Impact"],
   ["Google presence", "0 verified creatives", "Local + category + brand search", "Store walk-ins and bean orders captured"],
   ["Subscription base", "Not visible", "Monthly bean subscription", "Predictable D2C revenue per subscriber"],
   ["Store traffic", "Organic + word of mouth", "Radius campaigns + offers", "Measurable lift per outlet"],
   ["Site speed", "App-heavy Shopify stack", "Trimmed, audit-passing storefront", "Higher CVR across all channels"],
 ],
 "sources": [
   "Google Ads Transparency (region IN): 0 live creatives for thirdwavecoffeeroasters.com.",
   "thirdwavecoffee.in -> www.thirdwavecoffeeroasters.com (301); Shopify theme 133405212742; GTM present; 8+ apps detected in raw HTML.",
   "thirdwavecoffee.in/pages/contact: orders@thirdwavecoffee.in, +91 80 47108111, HSR Layout, Bengaluru 560102.",
   "Public coverage: USD 112M raised; Series D reported Aug 2026.",
   "Scope note: Google side only - Meta inventory was not verified in this pass.",
 ],
 "outreach": [
  ["Email 1 (Day 1): Verified - zero live Google ads for Third Wave",
   "Hi team,<br/><br/>I audit paid media for Bengaluru food brands. I checked Google Ads Transparency for your domain this week and found <b>zero</b> live creatives - verified, on the Google side.<br/><br/>For a brand with USD 112M raised and ~100 outlets, that means every 'coffee near me', 'cold brew delivery' and 'coffee beans online' query in your cities is answered by competitors. Local store campaigns are the cheapest walk-in channel a cafe chain can buy.<br/><br/>I have attached a 2-page audit with 3 fixes, starting with the one I would run this month. To be clear about scope: this audit verifies Google - I have not claimed anything about your Meta inventory. Open to 15 minutes?<br/><br/>- Smart Pursuit, Bengaluru | 7095024220"],
  ["Email 2 (Day 3): Local campaigns for your top 10 outlets",
   "Hi team,<br/><br/>Following the audit: the fastest win is a per-store radius campaign around your top 10 Bengaluru outlets, with a first-visit offer and measurement on store visits - not just clicks.<br/><br/>Cafe chains that run local ads typically see the effect in walk-ins within the first weeks, and you can scale store by store once the template is proven.<br/><br/>I can share the campaign structure and offer mechanics we would use.<br/><br/>- Smart Pursuit | 7095024220"],
  ["Email 3 (Day 7): Beans are a subscription, not a product",
   "Hi team,<br/><br/>Third idea from the audit. Your bean line competes with Blue Tokai and Sleepy Owl, who buy category search aggressively. Coffee beans are a monthly repeat purchase - the ideal profile for paid search plus a subscribe-and-save flow with free shipping.<br/><br/>One more thing worth fixing before you scale spend: the storefront runs 8+ apps on an older Shopify theme. Speed multiplies every rupee of paid traffic; we would audit that first.<br/><br/>- Smart Pursuit | 7095024220"],
  ["Email 4 (Day 14): Closing the file on Third Wave",
   "Hi team,<br/><br/>Final note: the audit's three fixes are (1) local store campaigns for the top 10 outlets, (2) a bean subscription engine with category search, (3) storefront speed before scaling spend.<br/><br/>If it helps, the audit is yours to keep regardless of whether we work together. And if you want a Meta-side check as step one, we can run that in a day.<br/><br/>- Smart Pursuit | 7095024220"],
 ],
 "verified_on": VERIFIED,
},
]
