# -*- coding: utf-8 -*-
"""Food / Bangalore audit leads - Part C (all data verified live on 02 Oct 2026)."""

VERIFIED = "02 OCT 2026"

LEADS_C = [
# ---------------------------------------------------------------- AKSHAYAKALPA
{
 "brand": "Akshayakalpa Organic",
 "website": "akshayakalpa.org",
 "instagram": "@akshayakalpa",
 "niche": "Organic Dairy & Farm-to-Door",
 "score": 8,
 "ads_active": 400,
 "headline": "The biggest paid footprint we found in Bengaluru food (~400 creatives) - landing on a site whose Contact Us page still carries a US template placeholder address.",
 "stats": [("~400", "Google creatives live"), ("24-36 hrs", "Farm to doorstep"), ("APEDA", "Certified organic"), ("INR 550 Cr", "FY26 target")],
 "contact": {"email": "support@akshayakalpa.org", "phone": "+91-9535388122", "entity": "Akshayakalpa Farms & Foods Pvt Ltd", "address": "Tiptur farms near Bengaluru; corporate office, Bengaluru, Karnataka (published contact: support@)"},
 "ad_intro": "Akshayakalpa Farms & Foods Pvt Ltd runs the largest paid ad inventory we found in this category - roughly 400 live Google creatives. The product story is world-class: APEDA-certified organic, milk chilled to 4C at farm level, 24-36 hours from milking to doorstep versus an industry norm of 72-96 hours, automated no-hand-touch milking, and a farmer-entrepreneurship model seeded in Nov 2010. Business momentum is strong - reported around INR 45-46 Cr monthly revenue with an FY26 target of INR 550 Cr, backed by a reported INR 350 Cr raise. The leaks are on the receiving side of that spend: the site, the contact paths, and the measurement layer that turns ~400 creatives into a learning system.",
 "ad_intelligence": [
   ["Google Ads (verified)", "~400 live creatives under Akshayakalpa Farms and Foods Pvt Ltd - the largest inventory in this audit set (Licious follows at ~300)."],
   ["What the brand publishes", "India's first certified organic dairy (brand claim); APEDA organic + Jaivik Bharat certified; farms at Tiptur (near Bengaluru), Shadnagar (Hyderabad), Pooriyambakkam (Chennai)."],
   ["Freshness claim (strongest asset)", "Milk chilled to 4C at farm level, moved in continuous cold chain, packed without human touch - 24-36 hours to doorstep vs 72-96 hours industry practice."],
   ["Live site defect captured", "akshayakalpa.org/contact-us still carries template placeholder text: '0123.456.789 - 2 Queen Street, California, USA' - a visible artifact a paid visitor can land on today."],
   ["Contact paths published", "Only support@akshayakalpa.org and +91-9535388122 are published. There is no separate distributor/partner, bulk or gifting enquiry path on the site."],
   ["Momentum (reported)", "Around INR 45-46 Cr/month revenue; FY26 target INR 550 Cr; reported INR 350 Cr raise with ABC Impact / Temasek participation; also distributed via BB Daily and SUPR Daily."],
 ],
 "scores": {
   "Creative Variety": [7, "#F59E0B"],
   "UGC & Social Proof": [6, "#F59E0B"],
   "Copy & Hook Strength": [7, "#F59E0B"],
   "Landing Page CRO": [4, "#EF4444"],
   "Tracking & CAPI": [5, "#F59E0B"],
   "Retargeting Depth": [5, "#F59E0B"],
 },
 "findings": [
   "<b>~400 creatives is a scale problem, not a scale win:</b> at this volume, spend thins out across assets and audiences unless there is a disciplined creative-testing system. Most brands running 400 creatives cannot name the top 10 performers - and if they cannot, the other 390 are paying for the lesson.",
   "<b>The site undermines the story:</b> a farm-to-door premium brand cannot have template placeholder text ('0123.456.789 - 2 Queen Street, California, USA') sitting on the Contact Us page its paid traffic can land on. It is a small fix with a direct trust cost while it is live.",
   "<b>No B2B path:</b> organic dairy has natural B2B lines - cafes, hotels, cloud kitchens, corporate pantry, gifting. The only published contact is a support line. Distributors, HoReCa buyers and corporate gifting leads have nowhere to go, so that demand never enters the funnel.",
   "<b>Freshness claim needs to be the landing hero:</b> '24-36 hours vs 72-96 hours industry' is the single most persuasive fact the brand owns. It belongs on the hero of every paid landing page, not buried in an FAQ answer.",
   "<b>Own the search term 'organic milk near me':</b> with ~400 creatives and an app + website + quick-commerce mix, the measurement layer must connect store-level demand to spend. Without clean CAPI/Enhanced Conversions, half of the signal is invisible and budget decisions are guesses.",
 ],
 "competitors": [
   ["Amul / Nandini / Heritage (conventional dairy majors)", "Distribution ubiquity and price trust.", "Compete on certified organic + antibiotic-free proof; never on price."],
   ["Country Delight (subscription-first dairy)", "Subscription mechanics and app retention delivering weekly orders.", "Akshayakalpa's story is stronger - wrap it in a subscription + retention system."],
   ["Other organic dairy brands", "Premium positioning, smaller scale.", "Win with certification proof, farm visits, and 24-36 hour freshness evidence."],
 ],
 "wins": [
   ["WIN 1 - Fix the funnel before feeding it more spend", "Remove placeholder/template artifacts, publish a real Bengaluru contact block, and rebuild the three highest-spend landing pages around the 24-36 hour freshness proof with subscription as the primary CTA.", "#EF4444", "#FEF2F2"],
   ["WIN 2 - Creative system: know your top 10", "Instrument all ~400 creatives, rank by CPA, kill the bottom third, and rebuild around 3 repeatable formats (proof film, farmer story, offer card) refreshed weekly from one shoot day. Same budget, sharper inventory.", "#F59E0B", "#FFFBEB"],
   ["WIN 3 - Open the B2B and gifting lines", "Add enquiry paths for HoReCa / corporate pantry / gifting with a simple form, case study and price-on-request flow - and run a small always-on campaign against them. This is demand you are currently refusing.", "#10B981", "#ECFDF5"],
 ],
 "impact": [
   ["Metric", "Current (live)", "After Wins (est.)", "Impact"],
   ["Creative inventory", "~400 creatives, unknown ranking", "Ranked: top 10 known, bottom third cut", "Same spend, better unit economics"],
   ["Landing trust", "Placeholder contact block live", "Clean, proof-led pages", "Higher conversion, protected premium"],
   ["B2B / gifting demand", "No enquiry path published", "Form + case study + always-on campaign", "New revenue line, low incremental spend"],
   ["Measurement", "Multi-channel, partially blind", "Clean CAPI + Enhanced Conversions", "Decisions backed by full signal"],
 ],
 "sources": [
   "Google Ads Transparency (region IN): ~400 live creatives; advertiser Akshayakalpa Farms and Foods Pvt Ltd.",
   "akshayakalpa.org (FAQ, company, privacy policy, contact pages): 4C farm chilling, 24-36 hr delivery claim, APEDA + Jaivik Bharat certification, farm locations, support@akshayakalpa.org / +91-9535388122, and live Contact Us page placeholder text.",
   "Reported figures: ~INR 45-46 Cr/month revenue, FY26 target INR 550 Cr, reported INR 350 Cr raise (ABC Impact / Temasek); distribution via BB Daily and SUPR Daily.",
   "Note on contact: brand publishes no marketing/partner address; support@akshayakalpa.org is the only official email on their own properties.",
 ],
 "outreach": [
  ["Email 1 (Day 1): ~400 live ads - and a California placeholder address on the landing page",
   "Hi team,<br/><br/>I audit paid media for food brands from Bengaluru. Your footprint is the biggest I found in this category: <b>~400 live Google creatives</b> under Akshayakalpa Farms and Foods Pvt Ltd. The product story behind it is world-class - 4C farm chilling, 24-36 hours to doorstep vs the 72-96 hour industry norm, APEDA certified.<br/><br/>One thing you can check in 30 seconds: the Contact Us page at akshayakalpa.org/contact-us currently contains template placeholder text - '0123.456.789 - 2 Queen Street, California, USA'. Your paid traffic lands on that page. It is a small fix and a direct trust cost while it is live.<br/><br/>Attached is the 7-page Paid Media and Measurement Audit, including what I would do with ~400 creatives to make them learn faster than they spend. Worth 15 minutes?<br/><br/>- Smart Pursuit, Bengaluru | 7095024220<br/><br/>P.S. I am writing to your published support address because the site does not list a marketing or partner contact - that is itself one of the findings."],
  ["Email 2 (Day 3): The problem with 400 creatives",
   "Hi team,<br/><br/>Following up on the audit. At ~400 creatives, the risk is not lack of creative - it is that nobody can name the top 10 performers, so the other 390 keep paying for lessons you already learned.<br/><br/>The fix is boring and effective: instrument everything, rank by CPA, cut the bottom third, and rebuild around three repeatable formats from one shoot day per week. Same budget, much sharper inventory.<br/><br/>I can show you the ranking framework we use - it takes about 20 minutes to walk through.<br/><br/>- Smart Pursuit | 7095024220"],
  ["Email 3 (Day 7): You are turning away B2B demand",
   "Hi team,<br/><br/>One more finding. Organic dairy has natural B2B lines - cafes, cloud kitchens, hotels, corporate pantry, gifting - and your site publishes only a support number. A distributor or a 200-box gifting enquiry has nowhere to land.<br/><br/>A simple enquiry page plus a small always-on campaign would open a revenue line you are currently refusing, at a fraction of the cost of new consumer acquisition.<br/><br/>Happy to map the flow (form, follow-up, pricing-on-request).<br/><br/>- Smart Pursuit | 7095024220"],
  ["Email 4 (Day 14): Closing the file on Akshayakalpa",
   "Hi team,<br/><br/>Final note from me. The audit's three fixes: (1) clean the funnel and rebuild the top landing pages around your 24-36 hour freshness proof, (2) rank and prune the 400-creative inventory into a weekly system, (3) open B2B and gifting enquiry paths.<br/><br/>The audit is yours to keep. If you would like help, we would start with the creative ranking - it usually pays for itself in the first fortnight.<br/><br/>- Smart Pursuit | 7095024220"],
 ],
 "verified_on": VERIFIED,
},
# ---------------------------------------------------------------- MILKY MIST
{
 "brand": "Milky Mist",
 "website": "milkymist.com",
 "instagram": "@milkymistdairy",
 "niche": "Dairy FMCG (IPO-bound)",
 "score": 8,
 "ads_active": 3,
 "headline": "An IPO-bound dairy major runs 3 live Google ads. The category searches are being answered by others.",
 "stats": [("3", "Google creatives live"), ("IPO", "Pre-listing company"), ("15+", "Product lines"), ("Bangalore", "Office, HSR Layout")],
 "contact": {"email": "customercare@milkymist.com", "phone": "1800-419-9000", "entity": "Milky Mist Dairy Food Limited", "address": "Ground Floor, No.530/B, 18th Main Rd, Sector 3, HSR Layout, Bengaluru 560102 (registered office: Perundurai, Erode 638057, TN; CIN U15200TZ2014PLC020554)"},
 "ad_intro": "Milky Mist Dairy Food Limited is a Tamil Nadu dairy major preparing for the public markets - the site carries a full IPO section, CSR, corporate governance, financial information, stock-exchange intimations and the SEBI Regulation 46 disclosures. Yet Google Ads Transparency shows only 3 live creatives. For a company that will be judged on demand durability and brand strength, that is a striking gap: category searches for paneer, curd, cheese and ghee are being answered by Amul, Nandini and quick-commerce private labels. There is also a strong Bengaluru story to lean on - the brand runs its office out of HSR Layout, a short walk from some of India's most competitive quick-commerce operations.",
 "ad_intelligence": [
   ["Google Ads (verified)", "3 live creatives; advertiser Milky Mist Dairy Food Limited."],
   ["Corporate status", "IPO section live on the corporate site, with CSR, corporate governance, financial information, stock-exchange intimations, analyst/investor conferences and SEBI Regulation 46 disclosures - i.e. a pre-listing company."],
   ["Footprint", "Registered office at Pattakkaranpalayam, Perundurai, Erode 638057, Tamil Nadu (CIN U15200TZ2014PLC020554); Bangalore office at HSR Layout, Bengaluru 560102; mega plant at Perundurai."],
   ["Product breadth", "Paneer, curd, fruit yogurt, premium yogurt, ice cream, condensed milk, ghee, cheese, butter, ready-to-drink, desserts, UHT and food enhancers - plus sub-brands Capella, Asal, Smartchef and Briyas."],
   ["Digital estate", "Corporate site on Wix (www.milkymist.com) plus a separate Shopify online store (shop.milkymist.com) - two properties, two journeys, one brand."],
   ["Published contacts", "customercare@milkymist.com for feedback/complaints; investor@milkymist.com (Company Secretary & Compliance Officer, Mr. S Prakash); toll-free 1800-419-9000, 9am-6pm Monday to Saturday."],
 ],
 "scores": {
   "Creative Variety": [3, "#EF4444"],
   "UGC & Social Proof": [4, "#EF4444"],
   "Copy & Hook Strength": [5, "#F59E0B"],
   "Landing Page CRO": [4, "#EF4444"],
   "Tracking & CAPI": [4, "#EF4444"],
   "Retargeting Depth": [3, "#EF4444"],
 },
 "findings": [
   "<b>A pre-IPO dairy brand with 3 live ads is leaving its own category to competitors:</b> paneer, curd, ghee, cheese and ice cream are all searched with high commercial intent. Every one of those searches is a chance for Amul or a quick-commerce private label to be chosen instead of Milky Mist.",
   "<b>Brand search defence:</b> with a listing on the horizon, brand-name searches should be protected and measured - if a competitor or a marketplace outbids your own name, you pay for it in both margin and mindshare.",
   "<b>Two properties, two journeys:</b> a Wix corporate site plus a separate Shopify store means the paid click, the brand story and the purchase path live in different places. Consolidating the journey (or at least the handoff) is a direct conversion win.",
   "<b>Quick-commerce is both a channel and a threat:</b> buyers now search 'paneer home delivery' inside apps. Unless Milky Mist owns the generic search layer on Google and reinforces brand recall, the aggregator owns the customer relationship - and the repeat purchase.",
   "<b>No subscription mechanics visible:</b> dairy is the most subscription-friendly food category in India (milk, curd, paneer weekly). A subscribe-and-save flow on the Shopify store would add predictable, higher-LTV revenue before the IPO window.",
 ],
 "competitors": [
   ["Amul / Nandini / Heritage", "Massive distribution + price trust + strong brand recall.", "Compete on quality proof (paneer texture, milk fat standards) and product-specific search."],
   ["Quick-commerce private labels", "Own the in-app search and 10-minute delivery.", "Own Google-level generic search and drive to a strong subscription offer."],
   ["Premium dairy D2C brands", "Subscription and packaging-led brands.", "Milky Mist's plant scale + product range is a moat - say it in the ads."],
 ],
 "wins": [
   ["WIN 1 - Category search moat", "Launch full-funnel Google search across brand, category and competitor terms ('paneer online', 'curd home delivery', 'ghee', 'fresh cheese') with product-specific landing pages on the Shopify store and clean tracking per SKU family.", "#EF4444", "#FEF2F2"],
   ["WIN 2 - Subscribe-and-save", "Add a monthly dairy subscription (milk, curd, paneer bundles) with free delivery thresholds and WhatsApp reminders - the highest-LTV mechanic in Indian dairy, and a strong pre-IPO demand story.", "#F59E0B", "#FFFBEB"],
   ["WIN 3 - Unify the digital journey", "Decide the primary purchase destination (Shopify store) and route all paid traffic there; use the Wix corporate site for brand, investor and B2B audiences. Then measure per-SKU-family to know what the spend is buying.", "#10B981", "#ECFDF5"],
 ],
 "impact": [
   ["Metric", "Current (live)", "After Wins (est.)", "Impact"],
   ["Google presence", "3 live creatives", "Brand + category + competitor search", "Category demand captured"],
   ["Recurring revenue", "No visible subscription", "Dairy subscribe-and-save", "Predictable, higher-LTV revenue pre-IPO"],
   ["Journey clarity", "Two properties, split funnel", "One purchase destination, measured", "Higher conversion per rupee"],
   ["Brand defence", "Partially unmanaged", "Brand terms owned + measured", "Lower CPC, protected mindshare"],
 ],
 "sources": [
   "Google Ads Transparency (region IN): 3 live creatives; advertiser Milky Mist Dairy Food Limited.",
   "milkymist.com/reach-us: customercare@milkymist.com, investor@milkymist.com, toll-free 1800-419-9000, registered office + CIN U15200TZ2014PLC020554, Bangalore office HSR Layout 560102.",
   "milkymist.com: product range and sub-brands (Capella, Asal, Smartchef, Briyas); IPO / CSR / corporate governance / financial information / SEBI Reg 46 disclosure pages live; Shopify store at shop.milkymist.com.",
 ],
 "outreach": [
  ["Email 1 (Day 1): 3 live Google ads for an IPO-bound dairy major",
   "Hi team,<br/><br/>I run paid-media audits for food brands from Bengaluru. I checked your live presence this week: Milky Mist Dairy Food Limited shows <b>3 live Google creatives</b> - while the corporate site carries a full IPO section, SEBI Reg 46 disclosures and investor pages.<br/><br/>That gap matters now: paneer, curd, ghee and cheese searches are high-intent purchase moments, and today they are being answered by Amul, Nandini and quick-commerce private labels. Before a listing, demand durability is part of the story you will be asked about.<br/><br/>Attached is the 7-page Paid Media and Measurement Audit. Open to 15 minutes?<br/><br/>- Smart Pursuit, Bengaluru | 7095024220"],
  ["Email 2 (Day 3): The dairy subscription you are not selling",
   "Hi team,<br/><br/>Following the audit: dairy is the most subscription-friendly category in India - milk, curd and paneer are bought weekly. A subscribe-and-save flow on the Shopify store (bundles, free-delivery threshold, WhatsApp reminders) adds predictable revenue and a much stronger demand story for the IPO window.<br/><br/>It also lowers CAC permanently: subscription customers compound instead of being re-bought every month.<br/><br/>I can share the offer mechanics and retention benchmarks we use.<br/><br/>- Smart Pursuit | 7095024220"],
  ["Email 3 (Day 7): Two websites, two journeys",
   "Hi team,<br/><br/>Third finding from the audit. Your brand currently lives across a Wix corporate site and a separate Shopify store. Paid traffic, brand story and purchase path are split - which quietly costs conversion on every campaign.<br/><br/>The fix: pick the Shopify store as the single purchase destination, keep the corporate site for brand, investor and B2B audiences, and measure per SKU family so you know exactly what the spend is buying.<br/><br/>Happy to map the handoff structure.<br/><br/>- Smart Pursuit | 7095024220"],
  ["Email 4 (Day 14): Closing the file on Milky Mist",
   "Hi team,<br/><br/>Final note: the audit's three fixes are (1) build the category search moat with product-specific landing pages, (2) launch subscribe-and-save for weekly dairy, (3) unify the paid journey onto the Shopify store and measure per SKU family.<br/><br/>The audit is yours to keep. If you would like to start, the search moat is the fastest measurable win.<br/><br/>- Smart Pursuit | 7095024220"],
 ],
 "verified_on": VERIFIED,
},
# ---------------------------------------------------------------- FROZEN BOTTLE
{
 "brand": "Frozen Bottle",
 "website": "frozenbottle.com",
 "instagram": "@frozen_bottle",
 "niche": "Desserts, Milkshakes & Franchise Retail",
 "score": 6,
 "ads_active": 11,
 "headline": "11 Google ads for a franchise chain - while every outlet's local demand goes unadvertised.",
 "stats": [("11", "Google creatives live"), ("Lubov", "Second brand in group"), ("Bengaluru", "HQ, Domlur"), ("Franchise", "Master + city model")],
 "contact": {"email": "vipul@frozenbottle.in", "phone": "080-48669920", "entity": "Munchbox Frozen Foods Pvt Ltd", "address": "35, K.R. Colony, Krishna Reddy Layout, Amarjyoti Layout, Domlur, Bengaluru 560071"},
 "ad_intro": "Frozen Bottle (Munchbox Frozen Foods Pvt Ltd) is a Bengaluru-born dessert chain - milkshakes, sundae jars, boba, bubble tea, Belgian waffles - that scaled through a city plus master-franchise model, and it runs two brands: Frozen Bottle and Lubov Patisserie. Verified Google inventory: 11 live creatives. For a chain whose growth depends on franchise enquiries and outlet footfall, the paid engine is barely switched on: no store-radius campaigns, no structured franchise-enquiry funnel, and a second brand (Lubov) with no visible paid support at all.",
 "ad_intelligence": [
   ["Google Ads (verified)", "11 live creatives; advertiser Munchbox Frozen Foods Pvt Ltd."],
   ["Business model", "Company-owned + franchise outlets, with dedicated franchise pages including 'Franchise by city' and 'Master franchise in India', plus corporate food booking - i.e. two revenue lines: consumer footfall and franchise sales."],
   ["Two brands, one engine", "Frozen Bottle plus Lubov Patisserie (lubov.in) - a premium patisserie brand with no visible paid activity in this pass."],
   ["HQ / contacts published", "35, K.R. Colony, Krishna Reddy Layout, Amarjyoti Layout, Domlur, Bengaluru 560071; franchise@frozenbottle.in / +91 9108131660 / +91 6366870312; partnership: vipul@frozenbottle.in; customer care 080-48669920, Mon-Fri 10am-6pm; cake orders +91 9108130460."],
   ["Live site defect captured", "Footer links to frozenbottle.com/pages/faqs while /pages/faq returns a 404 - a broken link buyers hit from the footer today."],
   ["Category context", "Dessert cafes compete on impulse and proximity; franchise brands compete for investor enquiries. Both demand types are addressable with cheap, local, always-on campaigns."],
 ],
 "scores": {
   "Creative Variety": [5, "#F59E0B"],
   "UGC & Social Proof": [5, "#F59E0B"],
   "Copy & Hook Strength": [5, "#F59E0B"],
   "Landing Page CRO": [4, "#EF4444"],
   "Tracking & CAPI": [4, "#EF4444"],
   "Retargeting Depth": [3, "#EF4444"],
 },
 "findings": [
   "<b>Franchise enquiries are a high-value, unadvertised funnel:</b> a single franchise sale is worth lakhs, and the buyer researches online first. With 11 creatives and no dedicated franchise campaign, that demand is largely organic - it should be a structured Google + Meta funnel with a numbers pack and a booking flow.",
   "<b>No store-radius layer:</b> dessert cafes win on proximity and impulse. Each outlet needs a 3-5 km radius campaign with an offer and per-store measurement - starting with the highest-performing Bengaluru stores.",
   "<b>Lubov Patisserie gets no paid support:</b> a premium sub-brand with its own site, no visible paid activity. It needs its own identity campaign (occasion cakes, corporate orders) rather than being folded into Frozen Bottle.",
   "<b>Broken footer link live:</b> the footer points to /pages/faqs while /pages/faq returns a 404 - small, but it is the kind of defect that erodes trust at the exact moment a franchise prospect is digging deeper.",
   "<b>Corporate food booking is buried:</b> offices order desserts for events - a dedicated B2B page + campaign is a low-cost, high-AOV line that currently depends on the visitor finding the page unaided.",
 ],
 "competitors": [
   ["National dessert chains", "Bigger outlet counts and stronger app presence.", "Win on local: per-store radius campaigns and franchise-prospect funnels."],
   ["Independent cafes & patisseries", "Hyperlocal loyalty and Instagram presence.", "Systematise what they do manually: offers, UGC and reminders per outlet."],
   ["Other franchise brands", "Aggressive franchise-marketing funnels with ROI maths published.", "Publish unit economics + run paid franchise campaigns; that is how franchise sales scale."],
 ],
 "wins": [
   ["WIN 1 - Franchise enquiry funnel", "A 'Franchise with us' campaign: landing page with investment range, ROI illustration, support model and a booking form - plus Google search for 'milkshake franchise', 'dessert franchise opportunity' and Meta retargeting for page viewers.", "#EF4444", "#FEF2F2"],
   ["WIN 2 - Store-radius campaigns", "Give the top 10 outlets 3-5 km radius campaigns with a store-specific offer and per-store tracking. This is the cheapest way to lift footfall and to prove the model before scaling.", "#F59E0B", "#FFFBEB"],
   ["WIN 3 - Give Lubov its own ad identity", "Run Lubov Patisserie as a separate brand: occasion cakes, corporate orders and premium gifting, with its own creatives, landing pages and retargeting. Two brands, two engines - not one.", "#10B981", "#ECFDF5"],
 ],
 "impact": [
   ["Metric", "Current (live)", "After Wins (est.)", "Impact"],
   ["Franchise enquiries", "Organic only", "Paid funnel + ROI pack + retargeting", "More qualified investor conversations"],
   ["Outlet footfall", "No local ad structure", "Radius campaigns on top 10 stores", "Measurable per-store lift"],
   ["Lubov revenue", "No paid activity", "Own brand campaigns", "New demand line at low cost"],
   ["B2B orders", "Page buried, unaided", "Campaign + dedicated landing", "Higher AOV corporate orders"],
 ],
 "sources": [
   "Google Ads Transparency (region IN): 11 live creatives; advertiser Munchbox Frozen Foods Pvt Ltd.",
   "frozenbottle.com (home, franchise, footer): HQ Domlur Bengaluru 560071; franchise@frozenbottle.in; vipul@frozenbottle.in (collaboration & partnership); customer care 080-48669920; cake orders +91 9108130460; franchise-by-city and master-franchise pages; Lubov Patisserie (lubov.in).",
   "Live defect: footer links /pages/faqs while /pages/faq returns a 404 (both checked 02 Oct 2026).",
 ],
 "outreach": [
  ["Email 1 (Day 1): 11 live ads for a franchise brand - the leak is in the funnel",
   "Hi team,<br/><br/>I audit paid media for Bengaluru food brands. I checked your live footprint: <b>11 Google creatives</b> under Munchbox Frozen Foods Pvt Ltd, plus two brands (Frozen Bottle and Lubov Patisserie) and a franchise model with city and master-franchise pages.<br/><br/>The gap: a single franchise sale is worth lakhs and the investor researches online first - but there is no structured paid funnel for franchise enquiries, and no store-radius campaigns for the outlets. Both are cheap to run and easy to measure.<br/><br/>One small thing you can fix today: the footer links to /pages/faqs, but /pages/faq returns a 404.<br/><br/>Attached is the 7-page Paid Media and Measurement Audit. Worth 15 minutes?<br/><br/>- Smart Pursuit, Bengaluru | 7095024220"],
  ["Email 2 (Day 3): The franchise funnel maths",
   "Hi team,<br/><br/>Following up on the audit. Compare the value of one franchise sale against the cost of a search click on 'milkshake franchise India' - the funnel pays for itself at a fraction of a single deal.<br/><br/>The structure: a franchise landing page with investment range, ROI illustration and support model, Google search on franchise-intent terms, and Meta retargeting for everyone who viewed the page. Add a booking form and you have a measurable pipeline.<br/><br/>Happy to share the page outline we use.<br/><br/>- Smart Pursuit | 7095024220"],
  ["Email 3 (Day 7): Lubov deserves its own ads",
   "Hi team,<br/><br/>Third finding from the audit. Lubov Patisserie has its own site but no visible paid activity - it is being carried by Frozen Bottle's brand rather than having its own demand engine.<br/><br/>Premium patisserie has obvious angles: occasion cakes, corporate orders and gifting. Separate creatives, separate landing pages, separate retargeting. Two brands should mean two engines.<br/><br/>I can sketch the first month's creative plan if useful.<br/><br/>- Smart Pursuit | 7095024220"],
  ["Email 4 (Day 14): Closing the file on Frozen Bottle",
   "Hi team,<br/><br/>Final note: the audit stands on three fixes - (1) build the franchise enquiry funnel, (2) store-radius campaigns for the top 10 outlets with per-store measurement, (3) give Lubov its own ad identity.<br/><br/>The audit is yours to keep. If you want to start, the franchise funnel is the highest-value build.<br/><br/>- Smart Pursuit | 7095024220"],
 ],
 "verified_on": VERIFIED,
},
]
